'use client';

import {FormEvent,useCallback,useEffect,useMemo,useState} from 'react';
import PasswordSettings from './PasswordSettings';

type MainModule='staff'|'tasks'|'violations'|'checklists'|'plans'|'reports'|'kpi'|'alerts'|'settings';
type FormModule=MainModule|'reminders'|'issues'|'violationError'|'checklistForm'|'checklistCriterion'|'feedback'|'rule';
type AnyRecord=Record<string,any>;

const BASE_DEPARTMENTS=['VỆ SINH MÔI TRƯỜNG','ĐỒ VẢI','GIÁM SÁT','DỤNG CỤ','VI PHẠM CHUNG'];
const MODULES:Array<{key:MainModule;label:string;number:string}>=([
 ['staff','NHÂN SỰ','1'],['tasks','GIAO VIỆC & NHẮC VIỆC','2'],['violations','CÔNG VIỆC TRỌNG ĐIỂM & ĐỘT XUẤT','3'],
 ['checklists','BẢNG KIỂM GIÁM SÁT','4'],['plans','KẾ HOẠCH TUẦN / THÁNG','6'],['reports','BÁO CÁO TỔNG HỢP MỚI','7'],
 ['kpi','KPI 100 ĐIỂM','8'],['alerts','CẢNH BÁO & LỊCH CÔNG VIỆC','9'],['settings','CÀI ĐẶT','10']
] as Array<[MainModule,string,string]>).map(([key,label,number])=>({key,label,number}));

function monthBounds(){const d=new Date();const from=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`;const last=new Date(d.getFullYear(),d.getMonth()+1,0);return {from,to:`${last.getFullYear()}-${String(last.getMonth()+1).padStart(2,'0')}-${String(last.getDate()).padStart(2,'0')}`};}
function text(value:any){if(value==null)return '';if(typeof value==='string'||typeof value==='number'||typeof value==='boolean')return String(value);try{return JSON.stringify(value)}catch{return '[Dữ liệu]';}}
function formatDate(value:any){const raw=text(value);return raw?raw.slice(0,10):'—';}
function normalize(value:any){return text(value).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d');}
function statusClass(value:any){const v=normalize(value);if(v.includes('hoan thanh')||v.includes('da khac phuc')||v.includes('da xong')||v==='dong')return 'ok';if(v.includes('qua han')||v.includes('khong dat')||v.includes('kem'))return 'danger';if(v.includes('dang')||v.includes('cho')||v.includes('chua'))return 'warn';return 'neutral';}
function paramsFor(module:MainModule,filters:AnyRecord){const p=new URLSearchParams({module});['from','to','department','person','title','priority','status','formCode','type'].forEach(k=>{if(filters[k])p.set(k,filters[k]);});['assignees','statuses'].forEach(k=>{if(filters[k]?.length)p.set(k,JSON.stringify(filters[k]));});return p.toString();}
function Badge({value}:{value:any}){return <span className={'status-badge '+statusClass(value)}>{text(value)||'—'}</span>;}

function SmartMulti({options,value,onChange,placeholder}:{options:string[];value:string[];onChange:(values:string[])=>void;placeholder:string}){
 const[open,setOpen]=useState(false);const[query,setQuery]=useState('');const filtered=options.filter(x=>!query||normalize(x).includes(normalize(query)));
 return <div className="smart-picker"><button type="button" className="smart-picker-toggle" onClick={()=>setOpen(x=>!x)}>{value.length?`${value.length} đã chọn`:placeholder}<span>⌄</span></button>{open&&<div className="smart-picker-menu"><input placeholder="Gõ để lọc..." value={query} onChange={e=>setQuery(e.target.value)}/><div className="smart-picker-options">{filtered.map(option=><label key={option}><input type="checkbox" checked={value.includes(option)} onChange={e=>onChange(e.target.checked?[...value,option]:value.filter(x=>x!==option))}/><span>{option}</span></label>)}</div><button type="button" className="smart-picker-clear" onClick={()=>onChange([])}>Xóa lựa chọn</button></div>}</div>;
}

function Field({label,value,onChange,type='text',children,wide=false,required=false}:{label:string;value:any;onChange:(value:string)=>void;type?:string;children?:React.ReactNode;wide?:boolean;required?:boolean}){return <label className={wide?'form-field wide':'form-field'}>{label}{children||<input type={type} value={text(value)} onChange={e=>onChange(e.target.value)} required={required}/>}</label>;}

export default function Home(){
 const bounds=useMemo(monthBounds,[]);const[authenticated,setAuthenticated]=useState<boolean|null>(null);const[active,setActive]=useState<MainModule|null>(null);const[payload,setPayload]=useState<AnyRecord>({rows:[],staff:[],departments:[]});const[homeAlerts,setHomeAlerts]=useState<AnyRecord[]>([]);const[health,setHealth]=useState<AnyRecord|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[loginError,setLoginError]=useState('');const[refresh,setRefresh]=useState(0);const[modal,setModal]=useState<AnyRecord|null>(null);const[form,setForm]=useState<AnyRecord>({});const[pendingAlert,setPendingAlert]=useState<AnyRecord|null>(null);
 const[filters,setFilters]=useState<AnyRecord>({from:bounds.from,to:bounds.to,department:'',person:'',title:'',priority:'',status:'',assignees:[],statuses:[],formCode:'',type:'TUẦN'});
 useEffect(()=>{fetch('/api/health',{cache:'no-store'}).then(r=>r.json()).then(setHealth).catch(()=>setHealth({ok:false}));fetch('/api/auth',{cache:'no-store'}).then(r=>r.json()).then(j=>setAuthenticated(Boolean(j.authenticated))).catch(()=>setAuthenticated(false));},[]);
 const load=useCallback(async()=>{if(!authenticated||!active||active==='settings')return;setLoading(true);setError('');try{const r=await fetch('/api/modules?'+paramsFor(active,filters),{cache:'no-store'});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.detail||j.error||'Không tải được dữ liệu');setPayload(j);}catch(e){setError(e instanceof Error?e.message:'Không tải được dữ liệu');setPayload({rows:[],staff:[],departments:[]});}finally{setLoading(false);}},[authenticated,active,JSON.stringify(filters),refresh]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{if(!authenticated||active)return;fetch('/api/modules?module=alerts',{cache:'no-store'}).then(r=>r.json()).then(j=>setHomeAlerts(j.rows||[])).catch(()=>setHomeAlerts([]));},[authenticated,active,refresh]);
 const departments=useMemo(()=>[...new Set([...BASE_DEPARTMENTS,...(payload.departments||[])])].filter(Boolean).sort((a,b)=>a.localeCompare(b,'vi')),[payload.departments]);
 const staffNames=useMemo(()=>((payload.staff||[]) as AnyRecord[]).map(x=>x.name).filter(Boolean),[payload.staff]);
 function setFilter(name:string,value:any){setFilters((prev:AnyRecord)=>({...prev,[name]:value}));}
 function openModule(key:MainModule){setActive(key);setError('');setPayload({rows:[],staff:[],departments:[]});}
 function openAlert(alert:AnyRecord){setPendingAlert(alert);setFilters((prev:AnyRecord)=>({...prev,from:'',to:'',department:alert.department||prev.department,person:alert.person||prev.person}));openModule(alert.target==='plans'?'plans':'tasks');}
 function openCreate(key:FormModule){
  const today=new Date().toISOString().slice(0,10);let next:AnyRecord={};
  if(key==='tasks')next={taskId:`CV${Date.now()}`,priority:'TRUNG BÌNH',status:'CHƯA BẮT ĐẦU',evalStatus:'CHƯA BẮT ĐẦU',startDate:today};
  if(key==='reminders')next={reminderId:`NV${Date.now()}`,date:today,status:'CHƯA THỰC HIỆN'};
  if(key==='staff')next={status:'Đang làm việc'};
  if(key==='violations')next={id:`VP${Date.now()}`,date:today,status:'Chưa xử lý'};
  if(key==='plans')next={id:'',type:filters.type||'TUẦN',fromDate:filters.from||bounds.from,toDate:filters.to||bounds.to,status:'CHƯA BẮT ĐẦU'};
  if(key==='issues')next={id:`TT${Date.now()}`,date:today,status:'CHƯA KHẮC PHỤC'};
  if(key==='reports')next={opinionId:`YK${Date.now()}`,fromDate:filters.from,toDate:filters.to,department:filters.department,status:'Đã lưu'};
  if(key==='checklists')next={date:today,details:[]};
  if(key==='checklistForm')next={status:'Hoạt động'};
  if(key==='checklistCriterion')next={status:'Hoạt động',allowImage:'Có',order:1};
  if(key==='violationError')next={status:'Hoạt động',level:'Nhắc nhở',score:0};
  if(key==='feedback')next={from:filters.from,to:filters.to,department:filters.department,person:filters.person};
  if(key==='rule')next={status:'Hoạt động',color:'#6C757D'};
  setForm(next);setModal({module:key});
 }
 function openEdit(key:FormModule,row:AnyRecord){setForm({...row,__module:key});setModal({module:key,row_no:row.row_no,source:row});}
 function change(name:string,value:any){setForm((prev:AnyRecord)=>({...prev,[name]:value}));}
 async function save(e:FormEvent){e.preventDefault();if(!modal)return;setError('');try{const current=e.currentTarget as HTMLFormElement;const fileInput=current.elements.namedItem('evidenceFile') as HTMLInputElement|null;const file=fileInput?.files?.[0];const body:AnyRecord={module:modal.module,row_no:modal.row_no,...form};if(modal.module==='kpi'){body.op='save_report';body.fromDate=filters.from;body.toDate=filters.to;body.department=filters.department;body.person=filters.person;}if(file&&['tasks','violations'].includes(modal.module))body.imageName=file.name;if(modal.module==='checklists')body.data=form;const response=await fetch('/api/modules',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'Không lưu được dữ liệu');if(file&&['tasks','violations','checklists'].includes(modal.module)){const evidence=new FormData();evidence.append('file',file);evidence.append('module',modal.module);evidence.append('legacy_id',String(result.id||form.taskId||form.id||`ROW${result.row_no}`));const upload=await fetch('/api/evidence',{method:'POST',body:evidence});const uploadResult=await upload.json();if(!upload.ok||!uploadResult.ok)throw new Error(uploadResult.error||'Đã lưu dữ liệu nhưng không tải được tài liệu minh chứng');}setModal(null);setRefresh(x=>x+1);}catch(e){setError(e instanceof Error?e.message:'Không lưu được dữ liệu');}}
 async function remove(module:FormModule,row:AnyRecord){if(!window.confirm('Xóa bản ghi này?'))return;try{const r=await fetch('/api/modules',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({module,op:'delete',row_no:row.row_no,type:row.type})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Không xóa được');setRefresh(x=>x+1);}catch(e){setError(e instanceof Error?e.message:'Không xóa được');}}
 async function planAction(op:string,row:AnyRecord){try{const r=await fetch('/api/modules',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({module:'plans',op,row_no:row.row_no,type:row.type,id:row.id})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Không cập nhật được kế hoạch');setRefresh(x=>x+1);}catch(e){setError(e instanceof Error?e.message:'Không cập nhật được kế hoạch');}}
 async function inlineUpdate(body:AnyRecord){try{const r=await fetch('/api/modules',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({module:'reports',op:'inline',...body})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Không cập nhật được báo cáo');setRefresh(x=>x+1);}catch(e){setError(e instanceof Error?e.message:'Không cập nhật được báo cáo');}}
 function resetFilters(){setFilters({from:bounds.from,to:bounds.to,department:'',person:'',title:'',priority:'',status:'',assignees:[],statuses:[],formCode:'',type:'TUẦN'});}
 useEffect(()=>{if(!pendingAlert||loading||!active)return;const source=pendingAlert.target==='reminders'?(payload.reminders||[]):(payload.rows||[]);const match=source.find((x:AnyRecord)=>x.row_no===pendingAlert.row_no||x.id===pendingAlert.id||x.taskId===pendingAlert.id);if(match){openEdit((pendingAlert.target==='reminders'?'reminders':active) as FormModule,match);setPendingAlert(null);}},[pendingAlert,loading,active,payload]);
 if(authenticated===null)return <div className="login-screen"><div className="login-card"><b>Đang kiểm tra phiên đăng nhập...</b></div></div>;
 if(!authenticated)return <div className="login-screen"><form className="login-card" onSubmit={async e=>{e.preventDefault();setLoginError('');const fd=new FormData(e.currentTarget);const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:fd.get('password')})});const j=await r.json();if(r.ok)setAuthenticated(true);else setLoginError(j.error||'Không đăng nhập được');}}><div className="brand-logo">KSNK<br/>115</div><h1>HỆ THỐNG QUẢN LÝ KSNK</h1><p>Nhập mật khẩu quản trị để tiếp tục</p><input type="password" name="password" placeholder="Mật khẩu" required autoFocus/>{loginError&&<div className="error-box">{loginError}</div>}<button>ĐĂNG NHẬP</button></form></div>;
 return <div className="app-shell"><header className="app-header"><div className="hospital-brand"><div className="brand-logo">KSNK<br/>115</div><div><h1>HỆ THỐNG QUẢN LÝ KSNK</h1><p>Bệnh viện 115</p></div></div><div className="header-title">QUẢN LÝ <span>KSNK</span></div></header><div className={'connection '+(health?.ok&&health?.supabaseDatabaseReachable?'connected':'')}>{health===null?'Đang kiểm tra kết nối...':health?.ok&&health?.supabaseDatabaseReachable?'Vercel + Supabase: ĐÃ KẾT NỐI':'Kiểm tra lại cấu hình Supabase'}</div>{active===null?<HomeScreen alerts={homeAlerts} onOpen={openModule} onOpenAlert={openAlert}/>:<ModuleScreen module={active} payload={payload} loading={loading} error={error} filters={filters} setFilter={setFilter} departments={departments} staffNames={staffNames} onReset={resetFilters} onCreate={()=>openCreate(active)} onCreateReminder={()=>openCreate('reminders')} onCreateError={()=>openCreate('violationError')} onCreateForm={()=>openCreate('checklistForm')} onCreateCriterion={()=>openCreate('checklistCriterion')} onCreateFeedback={()=>openCreate('feedback')} onCreateRule={()=>openCreate('rule')} onEdit={(row:AnyRecord)=>openEdit((row.__module||active) as FormModule,row)} onRemove={(row:AnyRecord)=>remove((row.__module||active) as FormModule,row)} onPlanAction={planAction} onInline={inlineUpdate} onOpenAlert={openAlert} onBack={()=>setActive(null)} onReload={()=>setRefresh(x=>x+1)}/>} {modal&&<EditModal module={modal.module as FormModule} form={form} payload={payload} departments={departments} change={change} onClose={()=>setModal(null)} onSave={save}/>}</div>;
}

function HomeScreen({alerts,onOpen,onOpenAlert}:{alerts:AnyRecord[];onOpen:(key:MainModule)=>void;onOpenAlert:(alert:AnyRecord)=>void}){return <main className="content-shell"><div className="home-alerts"><div className="section-title">⚠ CẢNH BÁO CẦN XỬ LÝ</div>{alerts.length?<div className="alert-strip">{alerts.slice(0,6).map((a,i)=><button key={i} onClick={()=>onOpenAlert(a)}><b>{a.level}</b><span>{a.title||a.kind}</span><small>{a.person||a.department||''} · {formatDate(a.date)}</small></button>)}</div>:<div className="empty compact">Không có cảnh báo trong 7 ngày tới.</div>}</div><div className="menu-grid">{MODULES.map(m=><button className="module-card" key={m.key} onClick={()=>onOpen(m.key)}><span className="module-number">{m.number}</span><h3>{m.label}</h3></button>)}</div></main>;}

function FilterBar({module,filters,setFilter,departments,staffNames,onReset,onReload}:{module:MainModule;filters:AnyRecord;setFilter:(key:string,value:any)=>void;departments:string[];staffNames:string[];onReset:()=>void;onReload:()=>void}){
 const dates=['tasks','violations','checklists','plans','reports','kpi'].includes(module);return <form className="module-filters" onSubmit={e=>{e.preventDefault();onReload();}}>{dates&&<><label>Từ ngày<input type="date" value={filters.from||''} onChange={e=>setFilter('from',e.target.value)}/></label><label>Đến ngày<input type="date" value={filters.to||''} onChange={e=>setFilter('to',e.target.value)}/></label></>}{['staff','violations','checklists','plans','reports','kpi','alerts'].includes(module)&&<label>Bộ phận<select value={filters.department||''} onChange={e=>setFilter('department',e.target.value)}><option value="">Tất cả bộ phận</option>{departments.map(x=><option key={x}>{x}</option>)}</select></label>}{['violations','plans','reports','alerts'].includes(module)&&<label>Nhân viên<select value={filters.person||''} onChange={e=>setFilter('person',e.target.value)}><option value="">Tất cả nhân viên</option>{staffNames.map(x=><option key={x}>{x}</option>)}</select></label>}{['staff','kpi'].includes(module)&&<label className="filter-wide">Tìm nhân viên<input placeholder="Nhập tên, không cần dấu..." value={filters.person||''} onChange={e=>setFilter('person',e.target.value)}/></label>}{module==='tasks'&&<><label className="filter-wide">Tìm tiêu đề<input placeholder="Nhập tên tiêu đề..." value={filters.title||''} onChange={e=>setFilter('title',e.target.value)}/></label><label>Mức ưu tiên<select value={filters.priority||''} onChange={e=>setFilter('priority',e.target.value)}><option value="">Tất cả ưu tiên</option>{(filters.optionsPriorities||[]).map((x:string)=><option key={x}>{x}</option>)}</select></label><SmartMulti options={staffNames} value={filters.assignees||[]} onChange={x=>setFilter('assignees',x)} placeholder="Nhiều người thực hiện"/><SmartMulti options={filters.optionsStatuses||[]} value={filters.statuses||[]} onChange={x=>setFilter('statuses',x)} placeholder="Nhiều trạng thái"/></>}{module==='checklists'&&<label>Phiếu giám sát<select value={filters.formCode||''} onChange={e=>setFilter('formCode',e.target.value)}><option value="">Tất cả phiếu</option>{(filters.optionsForms||[]).map((x:AnyRecord)=><option value={x.code} key={x.code}>{x.code} - {x.name}</option>)}</select></label>}{module==='plans'&&<><label>Loại kế hoạch<select value={filters.type||'TUẦN'} onChange={e=>setFilter('type',e.target.value)}><option>TUẦN</option><option>THÁNG</option></select></label><label>Trạng thái<select value={filters.status||''} onChange={e=>setFilter('status',e.target.value)}><option value="">Tất cả trạng thái</option>{(filters.optionsPlanStatuses||[]).map((x:string)=><option key={x}>{x}</option>)}</select></label></>}<button className="filter-submit">TÌM KIẾM</button><button type="button" className="filter-reset" onClick={onReset}>XÓA BỘ LỌC</button></form>;
}

function ModuleScreen({module,payload,loading,error,filters,setFilter,departments,staffNames,onReset,onCreate,onCreateReminder,onCreateError,onCreateForm,onCreateCriterion,onCreateFeedback,onCreateRule,onEdit,onRemove,onPlanAction,onInline,onOpenAlert,onBack,onReload}:{module:MainModule;payload:AnyRecord;loading:boolean;error:string;filters:AnyRecord;setFilter:(key:string,value:any)=>void;departments:string[];staffNames:string[];onReset:()=>void;onCreate:()=>void;onCreateReminder:()=>void;onCreateError:()=>void;onCreateForm:()=>void;onCreateCriterion:()=>void;onCreateFeedback:()=>void;onCreateRule:()=>void;onEdit:(row:AnyRecord)=>void;onRemove:(row:AnyRecord)=>void;onPlanAction:(op:string,row:AnyRecord)=>void;onInline:(body:AnyRecord)=>void;onOpenAlert:(alert:AnyRecord)=>void;onBack:()=>void;onReload:()=>void}){
 if(module==='settings')return <main><div className="module-toolbar"><button className="back-btn" onClick={onBack}>← TRANG CHỦ</button><h2>CÀI ĐẶT HỆ THỐNG</h2></div><section className="content-shell"><div className="panel-card"><h3>Đổi mật khẩu quản trị</h3><PasswordSettings/></div></section></main>;
 const title=MODULES.find(x=>x.key===module)?.label||module;const filterPayload={...filters,optionsPriorities:payload.options?.priorities||[],optionsStatuses:payload.options?.statuses||[],optionsForms:payload.forms||[],optionsPlanStatuses:payload.options?.statuses||[]};return <main><div className="module-toolbar"><button className="back-btn" onClick={onBack}>← TRANG CHỦ</button><h2>{title}</h2></div><section className="content-shell"><FilterBar module={module} filters={filterPayload} setFilter={setFilter} departments={departments} staffNames={staffNames} onReset={onReset} onReload={onReload}/>{error&&<div className="error-box">{error}</div>}{loading?<div className="panel-card"><p>Đang tải dữ liệu...</p></div>:<View module={module} payload={payload} onCreate={onCreate} onCreateReminder={onCreateReminder} onCreateError={onCreateError} onCreateForm={onCreateForm} onCreateCriterion={onCreateCriterion} onCreateFeedback={onCreateFeedback} onCreateRule={onCreateRule} onEdit={onEdit} onRemove={onRemove} onPlanAction={onPlanAction} onInline={onInline} onOpenAlert={onOpenAlert}/>}</section></main>;
}

function View({module,payload,onCreate,onCreateReminder,onCreateError,onCreateForm,onCreateCriterion,onCreateFeedback,onCreateRule,onEdit,onRemove,onPlanAction,onInline,onOpenAlert}:{module:MainModule;payload:AnyRecord;onCreate:()=>void;onCreateReminder:()=>void;onCreateError:()=>void;onCreateForm:()=>void;onCreateCriterion:()=>void;onCreateFeedback:()=>void;onCreateRule:()=>void;onEdit:(row:AnyRecord)=>void;onRemove:(row:AnyRecord)=>void;onPlanAction:(op:string,row:AnyRecord)=>void;onInline:(body:AnyRecord)=>void;onOpenAlert:(alert:AnyRecord)=>void}){
 const rows=(payload.rows||[]) as AnyRecord[];
 if(module==='tasks')return <div className="module-stack"><div className="panel-card toolbar-line"><b>{payload.total||rows.length} công việc</b><button className="add-btn" onClick={onCreate}>+ TẠO CÔNG VIỆC MỚI</button></div><div className="task-list">{rows.map(row=><article className="task-card" key={row.row_no}><div className="task-head"><div><span className="eyebrow">{row.assignee||'Chưa giao'} · {row.department||'Chưa chọn bộ phận'}</span><h3>{row.title||'Chưa có tiêu đề'}</h3></div><div className="badge-stack"><Badge value={row.status}/><Badge value={row.evalStatus}/></div></div><div className="task-description"><b>Nội dung / Mô tả</b><p>{row.description||'—'}</p></div><div className="task-meta"><span><b>Mức ưu tiên</b>{row.priority||'—'}</span><span><b>Từ ngày</b>{formatDate(row.startDate)}</span><span><b>Đến ngày</b>{formatDate(row.endDate)}</span><span><b>Ghi chú / Phản hồi quản lý</b>{row.qlNote||'—'}</span></div><div className="evidence-row"><b>Tài liệu minh chứng</b><EvidenceLinks module="tasks" legacyId={row.taskId||row.id} fallback={row.imageName}/></div><div className="card-actions"><button className="edit-btn" onClick={()=>onEdit(row)}>SỬA / BỔ SUNG</button><button className="danger" onClick={()=>onRemove(row)}>XÓA</button></div></article>)}</div><ReminderPanel rows={payload.reminders||[]} onCreate={onCreateReminder} onEdit={onEdit} onRemove={onRemove}/><Performance rows={payload.performance||[]}/></div>;
 if(module==='staff')return <div className="panel-card"><div className="toolbar-line"><b>{payload.total||rows.length} nhân viên</b><button className="add-btn" onClick={onCreate}>+ THÊM NHÂN VIÊN</button></div><DataTable rows={rows} columns={['id','name','department','position','phone','status']} headers={['Mã NV','Họ và tên','Bộ phận','Chức vụ','Số điện thoại','Trạng thái']} onEdit={onEdit} onRemove={onRemove}/></div>;
 if(module==='violations')return <div className="module-stack"><div className="panel-card toolbar-line"><b>{payload.total||rows.length} vi phạm</b><div className="card-actions"><button className="add-btn red" onClick={onCreate}>+ GHI NHẬN VI PHẠM</button><button className="edit-btn" onClick={onCreateError}>+ THÊM DANH MỤC LỖI</button></div></div><div className="panel-card"><DataTable rows={rows} columns={['date','person','department','errorName','level','score','recorder','status','note','imageName']} headers={['Ngày','Họ tên','Bộ phận','Tên lỗi','Mức độ','Điểm trừ','Người ghi nhận','Trạng thái','Ghi chú','Minh chứng']} onEdit={onEdit} onRemove={onRemove}/></div><div className="panel-card"><h3>Danh mục lỗi vi phạm</h3><DataTable rows={(payload.errorCatalog||[]).map((x:AnyRecord)=>({...x,__module:'violationError'}))} columns={['id','name','department','level','score','status']} headers={['Mã lỗi','Tên lỗi','Bộ phận','Mức độ','Điểm trừ','Trạng thái']} onEdit={onEdit} onRemove={onRemove}/></div></div>;
 if(module==='checklists')return <div className="module-stack"><div className="summary-cards"><div><b>{payload.summary?.total||0}</b><span>Phiếu đã lưu</span></div><div><b>{payload.summary?.pass||0}</b><span>Tiêu chí đạt</span></div><div><b>{payload.summary?.fail||0}</b><span>Tiêu chí không đạt</span></div><div><b>{payload.summary?.averageRate||0}%</b><span>Tỷ lệ đạt bình quân</span></div></div><div className="panel-card toolbar-line"><b>Phiếu giám sát</b><div className="card-actions"><button className="add-btn" onClick={onCreate}>+ LƯU PHIẾU GIÁM SÁT</button><button className="edit-btn" onClick={onCreateForm}>+ THÊM MẪU PHIẾU</button><button className="edit-btn" onClick={onCreateCriterion}>+ THÊM TIÊU CHÍ</button></div></div><div className="panel-card"><DataTable rows={rows} columns={['date','formCode','formName','person','department','supervisor','applied','pass','fail','rate','kpi','note','imageName']} headers={['Ngày','Mã phiếu','Tên phiếu','Nhân viên','Bộ phận','Giám sát','Áp dụng','Đạt','Không đạt','Tỷ lệ %','KPI','Ghi chú','Minh chứng']}/></div><div className="panel-card"><h3>Danh mục mẫu phiếu</h3><DataTable rows={(payload.forms||[]).map((x:AnyRecord)=>({...x,__module:'checklistForm'}))} columns={['code','name','department','description','criteriaCount','status']} headers={['Mã','Tên phiếu','Bộ phận','Mô tả','Số tiêu chí','Trạng thái']} onEdit={onEdit} onRemove={onRemove}/><h3>Danh mục tiêu chí</h3><DataTable rows={(payload.criteria||[]).map((x:AnyRecord)=>({...x,__module:'checklistCriterion'}))} columns={['id','formCode','group','content','detail','order','allowImage','status']} headers={['Mã','Mã phiếu','Nhóm','Nội dung','Chi tiết','STT','Ảnh','Trạng thái']} onEdit={onEdit} onRemove={onRemove}/></div></div>;
 if(module==='plans')return <div className="module-stack"><div className="summary-cards"><div><b>{payload.summary?.total||0}</b><span>Kế hoạch</span></div><div><b>{payload.summary?.done||0}</b><span>Hoàn thành</span></div><div><b>{payload.summary?.overdue||0}</b><span>Quá hạn</span></div><div><b>{payload.summary?.openIssues||0}</b><span>Tồn tại mở</span></div></div><div className="panel-card toolbar-line"><b>{payload.total||rows.length} kế hoạch</b><button className="add-btn" onClick={onCreate}>+ THÊM KẾ HOẠCH</button></div><div className="plan-list">{rows.map(row=><article className="plan-card" key={row.row_no}><div><span className="eyebrow">{row.type} · {row.department||'Chưa chọn bộ phận'} · {row.owner||'Chưa giao'}</span><h3>{row.content||'Chưa có nội dung'}</h3><p>{row.description||'—'}</p><p className="muted">Kết quả: {row.result||'—'} · Ghi chú: {row.note||'—'}</p></div><div className="plan-side"><Badge value={row.status}/><small>{formatDate(row.fromDate)} → {formatDate(row.toDate)}</small><div className="card-actions"><button className="edit-btn" onClick={()=>onEdit(row)}>SỬA</button><button className="edit-btn" onClick={()=>onPlanAction('complete',row)}>HOÀN THÀNH</button><button className="edit-btn" onClick={()=>onPlanAction('carry',row)}>CHUYỂN TIẾP</button><button className="edit-btn" onClick={()=>onPlanAction('reset',row)}>ĐẶT LẠI</button><button className="danger" onClick={()=>onRemove(row)}>XÓA</button></div></div></article>)}</div><div className="panel-card"><div className="toolbar-line"><h3>Tồn tại / Sự cố / Kiến nghị</h3><button className="add-btn" onClick={()=>onEdit({__module:'issues',id:'',date:new Date().toISOString().slice(0,10),status:'CHƯA KHẮC PHỤC'})}>+ THÊM TỒN TẠI</button></div><DataTable rows={(payload.issues||[]).map((x:AnyRecord)=>({...x,__module:'issues'}))} columns={['id','date','department','issue','cause','action','owner','deadline','status','recommendation','note']} headers={['Mã','Ngày','Bộ phận','Nội dung','Nguyên nhân','Khắc phục','Phụ trách','Hạn','Trạng thái','Kiến nghị','Ghi chú']} onEdit={onEdit} onRemove={onRemove}/></div></div>;
 if(module==='reports')return <div className="module-stack"><div className="summary-cards"><div><b>{payload.totals?.tasks||0}</b><span>Giao việc</span></div><div><b>{payload.totals?.taskDone||0}</b><span>CV hoàn thành</span></div><div><b>{payload.totals?.violations||0}</b><span>Vi phạm</span></div><div><b>{payload.totals?.checklists||0}</b><span>Bảng kiểm</span></div><div><b>{payload.totals?.plans||0}</b><span>Kế hoạch</span></div><div><b>{payload.totals?.issues||0}</b><span>Tồn tại</span></div></div><div className="panel-card"><h3>1. BÁO CÁO THEO BỘ PHẬN</h3><DataTable rows={rows} columns={['department','taskCount','completedTasks','overdueTasks','violationCount','violationPoints','checklistCount','checklistRate','checklistFails','planCount','openPlans','issueCount']} headers={['Bộ phận','Tổng CV','Hoàn thành','Quá hạn','Vi phạm','Điểm trừ','Phiếu kiểm','Tỷ lệ đạt %','Không đạt','Kế hoạch','Chưa xong','Tồn tại']}/></div><div className="panel-card"><h3>2. CHI TIẾT GIAO VIỆC — cập nhật trực tiếp</h3><ReportInlineTable rows={payload.tasks||[]} kind="TASK" onSave={onInline}/></div><div className="panel-card"><h3>3. KẾ HOẠCH TUẦN / THÁNG — cập nhật trực tiếp</h3><ReportInlineTable rows={payload.plans||[]} kind="PLAN" onSave={onInline}/></div><div className="panel-card"><h3>4. BẢNG KIỂM VÀ VI PHẠM</h3><DataTable rows={payload.checks||[]} columns={['date','formName','person','department','pass','fail','rate','kpi','note']} headers={['Ngày','Phiếu','Nhân viên','Bộ phận','Đạt','Không đạt','Tỷ lệ','KPI','Ghi chú']}/><DataTable rows={payload.violations||[]} columns={['date','person','department','errorName','points','status','note','imageName']} headers={['Ngày','Nhân viên','Bộ phận','Lỗi','Điểm trừ','Trạng thái','Ghi chú','Minh chứng']}/></div><div className="panel-card"><h3>5. PHÂN TÍCH LỖI VÀ TỒN TẠI</h3><p>{payload.special?.conclusion}</p><DataTable rows={payload.special?.errorStats||[]} columns={['errorName','count','totalPoints']} headers={['Tên lỗi','Số lần','Tổng điểm trừ']}/><DataTable rows={payload.issues||[]} columns={['id','date','department','issue','owner','deadline','status','recommendation']} headers={['Mã','Ngày','Bộ phận','Nội dung','Phụ trách','Hạn','Trạng thái','Kiến nghị']}/></div><div className="panel-card"><div className="toolbar-line"><h3>6. Ý KIẾN KHẮC PHỤC / BÁO CÁO</h3><button className="add-btn" onClick={onCreate}>+ GHI Ý KIẾN</button></div><DataTable rows={payload.opinions||[]} columns={['opinionId','fromDate','toDate','department','person','formName','opinion','enteredBy','status']} headers={['Mã','Từ','Đến','Bộ phận','Nhân viên','Phiếu','Ý kiến','Người nhập','Trạng thái']} onEdit={onEdit} onRemove={onRemove}/></div></div>;
 if(module==='kpi')return <div className="module-stack"><div className="summary-cards"><div><b>{payload.summary?.averageScore||0}</b><span>Điểm bình quân</span></div><div><b>{payload.summary?.totalTaskScore||0}</b><span>Điểm giao việc</span></div><div><b>{payload.summary?.totalChecklistScore||0}</b><span>Điểm bảng kiểm</span></div><div><b>{payload.summary?.totalViolationScore||0}</b><span>Điểm vi phạm</span></div></div><div className="panel-card toolbar-line"><b>{payload.total||rows.length} nhân sự KPI</b><div className="card-actions"><button className="add-btn" onClick={onCreate}>LƯU BẢNG KPI</button><button className="edit-btn" onClick={onCreateFeedback}>+ GÓP Ý KPI</button><button className="edit-btn" onClick={onCreateRule}>CẤU HÌNH QUY ĐỔI</button></div></div><div className="panel-card"><p>{payload.conclusion}</p><DataTable rows={rows} columns={['staffId','name','department','position','base','taskScore','checklistScore','violationScore','total','ranking','taskCount','checkCount','violationCount']} headers={['Mã NV','Nhân viên','Bộ phận','Chức vụ','Gốc','Giao việc','Bảng kiểm','Vi phạm','Tổng','Xếp loại','CV','Phiếu','VP']}/></div><div className="panel-card"><h3>Bảng quy đổi điểm</h3><DataTable rows={(payload.conversionRules||[]).map((x:AnyRecord)=>({...x,__module:'rule'}))} columns={['order','ranking','min','max','color']} headers={['STT','Xếp loại','Từ điểm','Đến điểm','Màu']} onEdit={onEdit}/></div><div className="panel-card"><h3>Góp ý KPI đã lưu</h3><DataTable rows={(payload.feedback||[]).map((x:AnyRecord)=>x.data?{...x.data,row_no:x.row_no}:x)} columns={['Mã ý kiến','Từ ngày','Đến ngày','Bộ phận','Nhân viên','Nội dung góp ý','Người nhập']} headers={['Mã','Từ','Đến','Bộ phận','Nhân viên','Nội dung','Người nhập']}/></div></div>;
 if(module==='alerts')return <div className="panel-card"><div className="toolbar-line"><b>{payload.total||rows.length} cảnh báo</b><small>Quá hạn · Hôm nay · 1–3 ngày · 4–7 ngày</small></div><DataTable rows={rows} columns={['level','kind','date','title','person','department']} headers={['Mức cảnh báo','Nguồn','Ngày','Nội dung','Nhân viên','Bộ phận']} actionRender={row=><button className="edit-btn" onClick={()=>onOpenAlert(row)}>MỞ &amp; CẬP NHẬT</button>}/></div>;
 return <div className="panel-card"><DataTable rows={rows}/></div>;
}

function ReminderPanel({rows,onCreate,onEdit,onRemove}:{rows:AnyRecord[];onCreate:()=>void;onEdit:(row:AnyRecord)=>void;onRemove:(row:AnyRecord)=>void}){return <div className="panel-card"><div className="toolbar-line"><h3>NHẮC VIỆC / GHI CHÚ (không tính KPI)</h3><button className="edit-btn" onClick={onCreate}>+ THÊM NHẮC VIỆC</button></div><DataTable rows={rows.map(x=>({...x,__module:'reminders'}))} columns={['date','title','note','person','status']} headers={['Ngày nhắc','Tiêu đề','Nội dung / Ghi chú','Người liên quan','Trạng thái']} onEdit={onEdit} onRemove={onRemove}/></div>;}
 function Performance({rows}:{rows:AnyRecord[]}){return <div className="panel-card"><h3>📊 TỔNG HỢP HIỆU SUẤT NHÂN SỰ — MỐC 100 ĐIỂM</h3><DataTable rows={rows} columns={['name','totalTasks','completed','overdue','excellent','good','fair','poor','bad','total','rank']} headers={['Nhân viên','Tổng CV','Hoàn thành','Quá hạn','Xuất sắc','Tốt','Khá','Chưa đạt','Kém','Tổng điểm','Xếp loại']}/></div>;}

function ReportInlineTable({rows,kind,onSave}:{rows:AnyRecord[];kind:'TASK'|'PLAN';onSave:(body:AnyRecord)=>void}){return <div className="table-wrap"><table><thead><tr><th>Ngày</th><th>Nội dung</th><th>Người phụ trách</th><th>Trạng thái</th><th>Đánh giá</th><th>Ghi chú / Kết quả</th><th></th></tr></thead><tbody>{rows.length?rows.map(row=><InlineReportRow key={`${kind}-${row.row_no}`} row={row} kind={kind} onSave={onSave}/>):<tr><td colSpan={7} className="empty-cell">Chưa có dữ liệu.</td></tr>}</tbody></table></div>;}
 function InlineReportRow({row,kind,onSave}:{row:AnyRecord;kind:'TASK'|'PLAN';onSave:(body:AnyRecord)=>void}){const[status,setStatus]=useState(row.status||'');const[evalStatus,setEvalStatus]=useState(row.evalStatus||'');const[note,setNote]=useState(kind==='TASK'?row.qlNote||'':row.note||'');return <tr><td>{formatDate(kind==='TASK'?row.endDate:row.toDate)}</td><td title={row.title||row.content}>{row.title||row.content||'—'}</td><td>{row.assignee||row.owner||'—'}</td><td><select value={status} onChange={e=>setStatus(e.target.value)}><option>CHƯA BẮT ĐẦU</option><option>ĐANG THỰC HIỆN</option><option>HOÀN THÀNH</option><option>QUÁ HẠN</option><option>CHUYỂN TIẾP</option></select></td><td>{kind==='TASK'?<select value={evalStatus} onChange={e=>setEvalStatus(e.target.value)}><option>CHƯA BẮT ĐẦU</option><option>XUẤT SẮC</option><option>TỐT</option><option>KHÁ</option><option>CHƯA ĐẠT</option><option>KÉM</option><option>QUÁ HẠN</option></select>:<Badge value={row.status}/>}</td><td><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Nhập ghi chú..."/></td><td><button className="edit-btn" onClick={()=>onSave({kind,id:row.id,row_no:row.row_no,planType:row.type,status,evalStatus,note})}>LƯU</button></td></tr>;}

function EvidenceLinks({module,legacyId,fallback}:{module:string;legacyId:any;fallback?:any}){const[files,setFiles]=useState<AnyRecord[]>([]);useEffect(()=>{if(!legacyId)return;fetch(`/api/evidence?module=${encodeURIComponent(module)}&legacy_id=${encodeURIComponent(String(legacyId))}`,{cache:'no-store'}).then(r=>r.json()).then(j=>setFiles(j.files||[])).catch(()=>setFiles([]));},[module,legacyId]);return <span className="evidence-links">{fallback&&<span className="muted">{text(fallback)}</span>}{files.map(file=><a key={file.id} href={file.url} target="_blank" rel="noreferrer">📎 {file.file_name}</a>)}{!fallback&&!files.length&&<span className="muted">Chưa có tệp</span>}</span>;}

function DataTable({rows,columns,headers,onEdit,onRemove,actionRender}:{rows:AnyRecord[];columns?:string[];headers?:string[];onEdit?:(row:AnyRecord)=>void;onRemove?:(row:AnyRecord)=>void;actionRender?:(row:AnyRecord)=>React.ReactNode}){const cols=columns||Array.from(new Set(rows.flatMap(x=>Object.keys(x.data||x)))).filter(x=>x!=='row_no'&&x!=='legacy_id'&&x!=='data').slice(0,14);return <div className="table-wrap"><table><thead><tr>{(headers||cols).map((x,i)=><th key={i}>{x}</th>)}{(onEdit||onRemove||actionRender)&&<th>Thao tác</th>}</tr></thead><tbody>{rows.length?rows.map((row,i)=><tr key={row.row_no||row.id||i}>{cols.map(c=><td key={c} title={text(row[c]??row.data?.[c])}>{text(row[c]??row.data?.[c])||'—'}</td>)}{(onEdit||onRemove||actionRender)&&<td className="actions-cell">{actionRender?.(row)}{onEdit&&<button className="edit-btn" onClick={()=>onEdit(row)}>SỬA</button>}{onRemove&&<button className="danger" onClick={()=>onRemove(row)}>XÓA</button>}</td>}</tr>):<tr><td colSpan={cols.length+1} className="empty-cell">Chưa có dữ liệu.</td></tr>}</tbody></table></div>;}

function EditModal({module,form,payload,departments,change,onClose,onSave}:{module:FormModule;form:AnyRecord;payload:AnyRecord;departments:string[];change:(key:string,value:any)=>void;onClose:()=>void;onSave:(e:FormEvent)=>void}){
 const staff=(payload.staff||[]) as AnyRecord[];const forms=(payload.forms||[]) as AnyRecord[];const criteria=(payload.criteria||[]) as AnyRecord[];const errors=(payload.errorCatalog||[]) as AnyRecord[];const allDepartments=[...new Set([...BASE_DEPARTMENTS,...departments])];const title=module==='tasks'?'GIAO VIỆC':module==='reminders'?'NHẮC VIỆC':module==='staff'?'NHÂN SỰ':module==='violations'?'GHI NHẬN VI PHẠM':module==='violationError'?'DANH MỤC LỖI':module==='plans'?'KẾ HOẠCH':module==='issues'?'TỒN TẠI / KIẾN NGHỊ':module==='reports'?'Ý KIẾN BÁO CÁO':module==='checklists'?'PHIẾU GIÁM SÁT':module==='checklistForm'?'MẪU PHIẾU':module==='checklistCriterion'?'TIÊU CHÍ BẢNG KIỂM':module==='feedback'?'GÓP Ý KPI':'QUY ĐỔI KPI';
 const details=(form.details||[]) as AnyRecord[];
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><form className="task-form" onSubmit={onSave}><div className="form-title"><h3>{title}</h3><button type="button" onClick={onClose}>×</button></div>
 {module==='staff'&&<div className="form-grid"><Field label="Mã NV" value={form.id} onChange={x=>change('id',x)} required/><Field label="Họ và tên" value={form.name} onChange={x=>change('name',x)} required/><Field label="Bộ phận" value={form.department} onChange={x=>change('department',x)}><select value={form.department||''} onChange={e=>change('department',e.target.value)}><option value="">Chọn bộ phận</option>{allDepartments.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Chức vụ" value={form.position} onChange={x=>change('position',x)}/><Field label="Số điện thoại" value={form.phone} onChange={x=>change('phone',x)}/><Field label="Trạng thái" value={form.status||'Đang làm việc'} onChange={x=>change('status',x)}/></div>}
 {module==='tasks'&&<div className="form-grid"><Field label="Tiêu đề công việc" value={form.title} onChange={x=>change('title',x)} wide required/><Field label="Nội dung / Mô tả" value={form.description} onChange={x=>change('description',x)} wide><textarea rows={4} value={form.description||''} onChange={e=>change('description',e.target.value)}/></Field><Field label="Người thực hiện" value={form.assignee} onChange={x=>change('assignee',x)}><select value={form.assignee||''} onChange={e=>change('assignee',e.target.value)}><option value="">Chọn nhân viên</option>{staff.map(x=><option key={x.name}>{x.name}</option>)}</select></Field><Field label="Mức ưu tiên" value={form.priority||'TRUNG BÌNH'} onChange={x=>change('priority',x)}/><Field label="Từ ngày" value={form.startDate} type="date" onChange={x=>change('startDate',x)}/><Field label="Đến ngày" value={form.endDate} type="date" onChange={x=>change('endDate',x)}/><Field label="Trạng thái" value={form.status||'CHƯA BẮT ĐẦU'} onChange={x=>change('status',x)}/><Field label="Đánh giá quản lý" value={form.evalStatus||'CHƯA BẮT ĐẦU'} onChange={x=>change('evalStatus',x)}/><Field label="Ghi chú nhân viên" value={form.note} onChange={x=>change('note',x)} wide/><Field label="Ghi chú / Phản hồi quản lý" value={form.qlNote} onChange={x=>change('qlNote',x)} wide><textarea rows={3} value={form.qlNote||''} onChange={e=>change('qlNote',e.target.value)}/></Field><label className="form-field wide evidence-label">Tài liệu minh chứng<input type="file" name="evidenceFile" accept="image/jpeg,image/png,image/webp,application/pdf"/><small>Tối đa 8 MB: JPG, PNG, WEBP hoặc PDF. Tệp được lưu riêng trong Supabase Storage.</small></label></div>}
 {module==='reminders'&&<div className="form-grid"><Field label="Ngày nhắc" value={form.date||form.reminderDate} type="date" onChange={x=>change('date',x)} required/><Field label="Tiêu đề nhắc việc" value={form.title} onChange={x=>change('title',x)} required/><Field label="Người liên quan" value={form.person} onChange={x=>change('person',x)}><select value={form.person||''} onChange={e=>change('person',e.target.value)}><option value="">Không bắt buộc</option>{staff.map(x=><option key={x.name}>{x.name}</option>)}</select></Field><Field label="Trạng thái" value={form.status||'CHƯA THỰC HIỆN'} onChange={x=>change('status',x)}/><Field label="Nội dung / Ghi chú" value={form.note} onChange={x=>change('note',x)} wide><textarea rows={5} value={form.note||''} onChange={e=>change('note',e.target.value)}/></Field></div>}
 {module==='violations'&&<div className="form-grid"><Field label="Ngày vi phạm" value={form.date} type="date" onChange={x=>change('date',x)} required/><Field label="Nhân viên" value={form.person} onChange={x=>change('person',x)}><select value={form.person||''} onChange={e=>{const s=staff.find(x=>x.name===e.target.value);change('person',e.target.value);change('staffId',s?.id||'');change('department',s?.department||'')}}><option value="">Chọn nhân viên</option>{staff.map(x=><option key={x.name}>{x.name}</option>)}</select></Field><Field label="Bộ phận" value={form.department} onChange={x=>change('department',x)}/><Field label="Mã lỗi / Tên lỗi" value={form.errorId} onChange={x=>change('errorId',x)}><select value={form.errorId||''} onChange={e=>{const er=errors.find(x=>x.id===e.target.value);change('errorId',e.target.value);change('errorName',er?.name||'');change('level',er?.level||'');change('score',er?.score||0)}}><option value="">Chọn lỗi</option>{errors.map(x=><option key={x.id} value={x.id}>{x.id} - {x.name}</option>)}</select></Field><Field label="Mức độ" value={form.level} onChange={x=>change('level',x)}/><Field label="Điểm trừ" value={form.score} type="number" onChange={x=>change('score',x)}/><Field label="Người ghi nhận" value={form.recorder} onChange={x=>change('recorder',x)}/><Field label="Trạng thái" value={form.status||'Chưa xử lý'} onChange={x=>change('status',x)}/><Field label="Ghi chú" value={form.note} onChange={x=>change('note',x)} wide><textarea rows={3} value={form.note||''} onChange={e=>change('note',e.target.value)}/></Field><label className="form-field wide evidence-label">Tài liệu / Hình ảnh minh chứng<input type="file" name="evidenceFile" accept="image/jpeg,image/png,image/webp,application/pdf"/><small>Tệp được lưu trong Supabase Storage.</small></label></div>}
 {module==='violationError'&&<div className="form-grid"><Field label="Mã lỗi" value={form.id} onChange={x=>change('id',x)} required/><Field label="Tên lỗi" value={form.name} onChange={x=>change('name',x)} required/><Field label="Bộ phận" value={form.department} onChange={x=>change('department',x)}/><Field label="Mức độ" value={form.level} onChange={x=>change('level',x)}/><Field label="Điểm trừ" value={form.score} type="number" onChange={x=>change('score',x)}/><Field label="Trạng thái" value={form.status||'Hoạt động'} onChange={x=>change('status',x)}/><Field label="Ghi chú" value={form.note} onChange={x=>change('note',x)} wide/></div>}
 {module==='plans'&&<div className="form-grid"><Field label="Loại kế hoạch" value={form.type||'TUẦN'} onChange={x=>change('type',x)}><select value={form.type||'TUẦN'} onChange={e=>change('type',e.target.value)}><option>TUẦN</option><option>THÁNG</option></select></Field><Field label="Từ ngày" value={form.fromDate} type="date" onChange={x=>change('fromDate',x)} required/><Field label="Đến ngày" value={form.toDate} type="date" onChange={x=>change('toDate',x)} required/><Field label="Bộ phận" value={form.department} onChange={x=>change('department',x)}><select value={form.department||''} onChange={e=>change('department',e.target.value)}><option value="">Chọn bộ phận</option>{allDepartments.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Nội dung kế hoạch" value={form.content} onChange={x=>change('content',x)} wide required/><Field label="Nội dung / Mô tả" value={form.description} onChange={x=>change('description',x)} wide><textarea rows={4} value={form.description||''} onChange={e=>change('description',e.target.value)}/></Field><Field label="Người phụ trách" value={form.owner} onChange={x=>change('owner',x)}><select value={form.owner||''} onChange={e=>change('owner',e.target.value)}><option value="">Chọn nhân viên</option>{staff.map(x=><option key={x.name}>{x.name}</option>)}</select></Field><Field label="Trạng thái" value={form.status||'CHƯA BẮT ĐẦU'} onChange={x=>change('status',x)}/><Field label="Kết quả" value={form.result} onChange={x=>change('result',x)} wide/><Field label="Ghi chú" value={form.note} onChange={x=>change('note',x)} wide><textarea rows={3} value={form.note||''} onChange={e=>change('note',e.target.value)}/></Field></div>}
 {module==='issues'&&<div className="form-grid"><Field label="Ngày ghi nhận" value={form.date} type="date" onChange={x=>change('date',x)}/><Field label="Bộ phận" value={form.department} onChange={x=>change('department',x)}><select value={form.department||''} onChange={e=>change('department',e.target.value)}><option value="">Chọn bộ phận</option>{allDepartments.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Tồn tại / Sự cố / Kiến nghị" value={form.issue} onChange={x=>change('issue',x)} wide required/><Field label="Nguyên nhân" value={form.cause} onChange={x=>change('cause',x)} wide/><Field label="Phương án khắc phục" value={form.action} onChange={x=>change('action',x)} wide/><Field label="Người phụ trách" value={form.owner} onChange={x=>change('owner',x)}><select value={form.owner||''} onChange={e=>change('owner',e.target.value)}><option value="">Chọn nhân viên</option>{staff.map(x=><option key={x.name}>{x.name}</option>)}</select></Field><Field label="Hạn xử lý" value={form.deadline} type="date" onChange={x=>change('deadline',x)}/><Field label="Trạng thái" value={form.status||'CHƯA KHẮC PHỤC'} onChange={x=>change('status',x)}/><Field label="Kiến nghị" value={form.recommendation} onChange={x=>change('recommendation',x)} wide/><Field label="Ghi chú" value={form.note} onChange={x=>change('note',x)} wide/></div>}
 {module==='checklists'&&<div className="form-grid"><Field label="Ngày giám sát" value={form.date} type="date" onChange={x=>change('date',x)} required/><Field label="Bộ phận" value={form.department} onChange={x=>change('department',x)}><select value={form.department||''} onChange={e=>change('department',e.target.value)}><option value="">Chọn bộ phận</option>{allDepartments.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Nhân viên" value={form.staffName} onChange={x=>change('staffName',x)}><select value={form.staffName||''} onChange={e=>{const s=staff.find(x=>x.name===e.target.value);change('staffName',e.target.value);change('staffId',s?.id||'');change('department',s?.department||form.department||'')}}><option value="">Chọn nhân viên</option>{staff.map(x=><option key={x.name}>{x.name}</option>)}</select></Field><Field label="Người giám sát" value={form.supervisor} onChange={x=>change('supervisor',x)}/><Field label="Phiếu giám sát" value={form.formCode} onChange={x=>change('formCode',x)}><select value={form.formCode||''} onChange={e=>{const selected=forms.find(x=>x.code===e.target.value);change('formCode',e.target.value);change('formName',selected?.name||'');change('details',criteria.filter(x=>x.formCode===e.target.value).map(x=>({criterionCode:x.id,group:x.group,content:x.content,detail:x.detail,order:x.order,result:'',note:''})))}}><option value="">Chọn phiếu</option>{forms.map(x=><option key={x.code} value={x.code}>{x.code} - {x.name}</option>)}</select></Field><Field label="Khu vực" value={form.area} onChange={x=>change('area',x)}/><Field label="Ca" value={form.shift} onChange={x=>change('shift',x)}/><Field label="Ghi chú" value={form.note} onChange={x=>change('note',x)} wide/><div className="wide checklist-editor">{details.map((d,i)=><div className="criterion-row" key={i}><span><b>{i+1}. {d.content}</b><small>{d.detail||''}</small></span><select value={d.result||''} onChange={e=>change('details',details.map((x,j)=>j===i?{...x,result:e.target.value}:x))}><option value="">Chưa chấm</option><option>ĐẠT</option><option>KHÔNG ĐẠT</option><option>KHÔNG ÁP DỤNG</option></select><input placeholder="Ghi chú nếu không đạt" value={d.note||''} onChange={e=>change('details',details.map((x,j)=>j===i?{...x,note:e.target.value}:x))}/></div>)}</div><label className="form-field wide evidence-label">Tài liệu minh chứng phiếu<input type="file" name="evidenceFile" accept="image/jpeg,image/png,image/webp,application/pdf"/></label></div>}
 {module==='checklistForm'&&<div className="form-grid"><Field label="Mã phiếu" value={form.code} onChange={x=>change('code',x)} required/><Field label="Tên phiếu" value={form.name} onChange={x=>change('name',x)} required/><Field label="Bộ phận" value={form.department} onChange={x=>change('department',x)}/><Field label="Trạng thái" value={form.status||'Hoạt động'} onChange={x=>change('status',x)}/><Field label="Mô tả" value={form.description} onChange={x=>change('description',x)} wide/></div>}
 {module==='checklistCriterion'&&<div className="form-grid"><Field label="Mã tiêu chí" value={form.id} onChange={x=>change('id',x)} required/><Field label="Mã phiếu" value={form.formCode} onChange={x=>change('formCode',x)}><select value={form.formCode||''} onChange={e=>change('formCode',e.target.value)}><option value="">Chọn phiếu</option>{forms.map(x=><option key={x.code}>{x.code}</option>)}</select></Field><Field label="Bộ phận" value={form.department} onChange={x=>change('department',x)}/><Field label="Nhóm tiêu chí" value={form.group} onChange={x=>change('group',x)}/><Field label="STT" value={form.order} type="number" onChange={x=>change('order',x)}/><Field label="Cho phép hình ảnh" value={form.allowImage||'Có'} onChange={x=>change('allowImage',x)}/><Field label="Nội dung tiêu chí" value={form.content} onChange={x=>change('content',x)} wide required/><Field label="Nội dung chi tiết" value={form.detail} onChange={x=>change('detail',x)} wide><textarea rows={4} value={form.detail||''} onChange={e=>change('detail',e.target.value)}/></Field><Field label="Trạng thái" value={form.status||'Hoạt động'} onChange={x=>change('status',x)}/></div>}
 {module==='reports'&&<div className="form-grid"><Field label="Mã ý kiến" value={form.opinionId} onChange={x=>change('opinionId',x)}/><Field label="Từ ngày" value={form.fromDate} type="date" onChange={x=>change('fromDate',x)}/><Field label="Đến ngày" value={form.toDate} type="date" onChange={x=>change('toDate',x)}/><Field label="Bộ phận" value={form.department} onChange={x=>change('department',x)}/><Field label="Nhân viên" value={form.person} onChange={x=>change('person',x)}/><Field label="Mã phiếu / báo cáo" value={form.reportId} onChange={x=>change('reportId',x)}/><Field label="Người nhập" value={form.enteredBy} onChange={x=>change('enteredBy',x)}/><Field label="Ý kiến khắc phục của tổ trưởng" value={form.opinion} onChange={x=>change('opinion',x)} wide><textarea rows={5} value={form.opinion||''} onChange={e=>change('opinion',e.target.value)}/></Field></div>}
 {module==='feedback'&&<div className="form-grid"><Field label="Từ ngày" value={form.from} type="date" onChange={x=>change('from',x)} required/><Field label="Đến ngày" value={form.to} type="date" onChange={x=>change('to',x)} required/><Field label="Bộ phận" value={form.department} onChange={x=>change('department',x)}/><Field label="Nhân viên" value={form.person} onChange={x=>change('person',x)}/><Field label="Nội dung góp ý" value={form.text} onChange={x=>change('text',x)} wide><textarea rows={5} value={form.text||''} onChange={e=>change('text',e.target.value)}/></Field></div>}
 {module==='kpi'&&<div className="panel-card compact"><b>Lưu kết quả KPI theo đúng công thức của Script:</b><p>100 + điểm giao việc + điểm bảng kiểm − điểm vi phạm. Bảng quy đổi hiện tại được đọc từ DM_QUYDOI_KPI và các dòng sẽ được ghi vào KPI_100_DIEM.</p></div>}
 {module==='rule'&&<div className="form-grid"><Field label="STT" value={form.order} type="number" onChange={x=>change('order',x)}/><Field label="Xếp loại" value={form.ranking} onChange={x=>change('ranking',x)} required/><Field label="Từ điểm" value={form.min} type="number" onChange={x=>change('min',x)}/><Field label="Đến điểm" value={form.max} type="number" onChange={x=>change('max',x)}/><Field label="Màu" value={form.color} onChange={x=>change('color',x)}/><Field label="Trạng thái" value={form.status||'Hoạt động'} onChange={x=>change('status',x)}/></div>}
 <div className="form-actions"><button type="button" onClick={onClose}>HỦY</button><button className="save-btn">LƯU DỮ LIỆU</button></div></form></div>;
}
