'use client';

import {FormEvent,useEffect,useState} from 'react';

type DepartmentRow={row_no:number;name:string;status:string;referenceCount:number;previousName?:string};
type GeneralSettings={unitName:string;softwareName:string;cssdReportUrl:string;cssdSourceSheet:string;cssdTargetPerDay:string;logoUrl:string};

function SettingsMessage({message,error=false}:{message:string;error?:boolean}){return message?<p className={error?'settings-message error':'settings-message'} role="status">{message}</p>:null;}

function GeneralSettings(){
 const[form,setForm]=useState<GeneralSettings>({unitName:'BỆNH VIỆN 115',softwareName:'HỆ THỐNG QUẢN LÝ KSNK',cssdReportUrl:'',cssdSourceSheet:'DỤNG CỤ BẬN',cssdTargetPerDay:'',logoUrl:''});
 const[logoFile,setLogoFile]=useState<File|null>(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState(false);
  useEffect(()=>{const load=async()=>{try{const[generalResponse,logoResponse]=await Promise.all([fetch('/api/settings/general',{cache:'no-store'}),fetch('/api/settings/logo',{cache:'no-store'})]);const result=await generalResponse.json();const logo=await logoResponse.json();if(!generalResponse.ok||!result.ok)throw new Error(result.error||'Không đọc được cài đặt');setForm({unitName:result.unitName,softwareName:result.softwareName,cssdReportUrl:result.cssdReportUrl||'',cssdSourceSheet:result.cssdSourceSheet||'DỤNG CỤ BẬN',cssdTargetPerDay:result.cssdTargetPerDay||'',logoUrl:logo.ok?logo.logoUrl||'':''});}catch(reason){setError(true);setMessage(reason instanceof Error?reason.message:'Không đọc được cài đặt hệ thống');}};void load();},[]);
 async function submit(event:FormEvent<HTMLFormElement>){
  event.preventDefault();setBusy(true);setMessage('');setError(false);
  try{const{logoUrl:_,...settings}=form;const response=await fetch('/api/settings/general',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'Không lưu được cài đặt');let nextLogo=form.logoUrl;if(logoFile){const logoForm=new FormData();logoForm.append('file',logoFile);const logoResponse=await fetch('/api/settings/logo',{method:'POST',body:logoForm});const logoResult=await logoResponse.json();if(!logoResponse.ok||!logoResult.ok)throw new Error(logoResult.error||'Không lưu được logo hệ thống');nextLogo=logoResult.logoUrl||'';setLogoFile(null);}setForm({unitName:result.unitName,softwareName:result.softwareName,cssdReportUrl:result.cssdReportUrl||'',cssdSourceSheet:result.cssdSourceSheet||'DỤNG CỤ BẬN',cssdTargetPerDay:result.cssdTargetPerDay||'',logoUrl:nextLogo});window.dispatchEvent(new Event('ksnk-general-settings-updated'));setMessage('Đã lưu tên hiển thị, logo và cấu hình nguồn dữ liệu DỤNG CỤ.');}
  catch(reason){setError(true);setMessage(reason instanceof Error?reason.message:'Không kết nối được máy chủ');}finally{setBusy(false);}
 }
 return <section className="settings-section"><div className="settings-section-heading"><div><h4>TÊN HIỂN THỊ, LOGO VÀ NGUỒN BÁO CÁO DỤNG CỤ</h4><p className="settings-note">Tên hệ thống dùng chung cho thanh menu và tiêu đề; logo tải lên sẽ thay logo mặc định. Link Google Sheet cần được cấp quyền đọc hoặc dùng link xuất CSV HTTPS.</p></div></div><form onSubmit={submit}><div className="settings-grid"><label>Tên đơn vị<input value={form.unitName} onChange={event=>setForm(previous=>({...previous,unitName:event.target.value}))} maxLength={160} required/></label><label>Tên hệ thống phần mềm<input value={form.softwareName} onChange={event=>setForm(previous=>({...previous,softwareName:event.target.value}))} maxLength={160} required/></label><label className="wide">Logo hệ thống<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>setLogoFile(event.target.files?.[0]||null)} disabled={busy}/>{form.logoUrl&&<img className="settings-logo-preview" src={form.logoUrl} alt="Logo hiện tại"/>}<small className="settings-note">JPG, PNG hoặc WEBP, tối đa 4 MB.</small></label><label className="wide">Đường link dữ liệu DỤNG CỤ<input type="url" value={form.cssdReportUrl} onChange={event=>setForm(previous=>({...previous,cssdReportUrl:event.target.value}))} placeholder="https://docs.google.com/spreadsheets/d/..." maxLength={1000}/><small className="settings-note">Dùng link Spreadsheet; hệ thống tự đọc dạng CSV theo gid đang chọn. Link riêng tư cần bật quyền đọc phù hợp.</small></label><label>Tên sheet nguồn<input value={form.cssdSourceSheet} onChange={event=>setForm(previous=>({...previous,cssdSourceSheet:event.target.value}))} maxLength={160}/></label><label>Mục tiêu bộ dụng cụ/ngày<input type="number" min="0" value={form.cssdTargetPerDay} onChange={event=>setForm(previous=>({...previous,cssdTargetPerDay:event.target.value}))} placeholder="0 = chưa đặt định mức"/></label></div><SettingsMessage message={message} error={error}/><button className="back-btn" disabled={busy}>{busy?'ĐANG LƯU...':'LƯU CÀI ĐẶT'}</button></form></section>;
}

function DepartmentSettings(){
 const[rows,setRows]=useState<DepartmentRow[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[name,setName]=useState('');const[editing,setEditing]=useState<number|null>(null);const[editName,setEditName]=useState('');const[message,setMessage]=useState('');const[error,setError]=useState(false);
 async function load(){
  setLoading(true);
  try{const response=await fetch('/api/settings/departments',{cache:'no-store'});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'Không đọc được danh sách bộ phận');const catalog=(result.catalog?.length?result.catalog:(result.departments||[]).map((department:string,index:number)=>({row_no:-(index+1),name:department,status:'Hoạt động',referenceCount:result.referenceCounts?.[department]||0})));setRows(catalog);setError(false);}
  catch(reason){setError(true);setMessage(reason instanceof Error?reason.message:'Không đọc được danh sách bộ phận');}finally{setLoading(false);}
 }
 useEffect(()=>{void load();},[]);
 async function mutate(action:string,body:Record<string,unknown>){
  setBusy(true);setMessage('');setError(false);
  try{const response=await fetch('/api/settings/departments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...body})});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'Không lưu được bộ phận');setMessage(result.message||'Đã cập nhật danh mục bộ phận.');setEditing(null);setName('');setEditName('');await load();}
  catch(reason){setError(true);setMessage(reason instanceof Error?reason.message:'Không kết nối được máy chủ');}finally{setBusy(false);}
 }
 async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();if(name.trim())await mutate('add',{name:name.trim()});}
 function beginEdit(row:DepartmentRow){setEditing(row.row_no);setEditName(row.name);setMessage('');setError(false);}
 return <section className="settings-section department-settings"><div className="settings-section-heading"><div><h4>CÀI ĐẶT TÊN BỘ PHẬN</h4><p className="settings-note">Thêm, sửa tên và xóa khỏi danh sách lựa chọn. Xóa sẽ bị chặn nếu bộ phận còn được nhân sự, công việc hoặc hồ sơ khác tham chiếu.</p></div></div><form className="department-add-form" onSubmit={add}><label>Thêm bộ phận mới<input value={name} onChange={event=>setName(event.target.value)} placeholder="Nhập tên bộ phận..." maxLength={120} required/></label><button className="add-btn" disabled={busy}>+ THÊM BỘ PHẬN</button></form><SettingsMessage message={message} error={error}/>{loading?<p>Đang tải danh mục bộ phận...</p>:<div className="table-wrap department-settings-table"><table><thead><tr><th>Tên bộ phận</th><th>Trạng thái</th><th>Đang tham chiếu</th><th>Thao tác</th></tr></thead><tbody>{rows.length?rows.map(row=><tr key={row.row_no}><td>{editing===row.row_no?<input className="department-edit-input" value={editName} onChange={event=>setEditName(event.target.value)} maxLength={120}/>:<b>{row.name}</b>}{row.previousName&&<small className="department-previous-name">Tên trước: {row.previousName}</small>}</td><td><span className={row.status==='Hoạt động'?'department-active':'department-inactive'}>{row.status}</span></td><td>{row.referenceCount||0}</td><td className="actions-cell">{row.status==='Hoạt động'&&editing===row.row_no?<><button type="button" className="edit-btn" disabled={busy} onClick={()=>mutate('edit',{oldName:row.name,newName:editName.trim()})}>LƯU TÊN</button><button type="button" className="filter-reset" onClick={()=>setEditing(null)}>HỦY</button></>:row.status==='Hoạt động'?<><button type="button" className="edit-btn" disabled={busy} onClick={()=>beginEdit(row)}>SỬA TÊN</button><button type="button" className="danger" disabled={busy} onClick={()=>{if(window.confirm(`Xóa bộ phận "${row.name}" khỏi danh sách lựa chọn?`))void mutate('delete',{name:row.name});}}>XÓA</button></>:<span className="muted">Đã lưu lịch sử</span>}</td></tr>):<tr><td colSpan={4} className="empty-cell">Chưa có danh mục bộ phận.</td></tr>}</tbody></table></div>}</section>;
}

export default function PasswordSettings(){
 const[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[done,setDone]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){
  event.preventDefault();const form=event.currentTarget;setBusy(true);setMessage('');
  const fields=new FormData(form);
  try{const response=await fetch('/api/settings/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(fields))});const result=await response.json();if(!response.ok)throw new Error(result.error||'Không đổi được mật khẩu');form.reset();setDone(true);setMessage('Đã đổi mật khẩu. Các phiên đăng nhập cũ đã hết hiệu lực. Vui lòng đăng nhập bằng mật khẩu mới.');}
  catch(reason){setMessage(reason instanceof Error?reason.message:'Không kết nối được máy chủ');}finally{setBusy(false);}
 }
 return <div className="settings-stack"><section className="settings-section"><h4>ĐỔI MẬT KHẨU QUẢN TRỊ</h4><p className="settings-note">Mật khẩu mới áp dụng ngay, không cần triển khai lại Vercel.</p><form onSubmit={submit}><div className="settings-grid"><label>Mật khẩu hiện tại<input name="currentPassword" type="password" autoComplete="current-password" required disabled={busy||done}/></label><label>Mật khẩu mới<input name="newPassword" type="password" autoComplete="new-password" minLength={12} required disabled={busy||done}/></label><label>Xác nhận mật khẩu mới<input name="confirmPassword" type="password" autoComplete="new-password" minLength={12} required disabled={busy||done}/></label></div><p role="status">{message}</p>{done?<a href="/">ĐĂNG NHẬP LẠI</a>:<button className="back-btn" disabled={busy}>{busy?'ĐANG LƯU...':'LƯU MẬT KHẨU MỚI'}</button>}</form></section><GeneralSettings/><DepartmentSettings/></div>;
}
