type AnyRecord=Record<string,any>;

function text(value:unknown){return value==null?'':String(value).trim();}
function norm(value:unknown){return text(value).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/\s+/g,' ');}
function ymd(value:unknown){const raw=text(value);if(!raw)return '';const iso=raw.match(/(\d{4}-\d{2}-\d{2})/);if(iso)return iso[1];const dmy=raw.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/);if(dmy)return `${dmy[3]}-${String(dmy[2]).padStart(2,'0')}-${String(dmy[1]).padStart(2,'0')}`;const serial=Number(raw);if(Number.isFinite(serial)&&serial>20000&&serial<80000){const date=new Date(Date.UTC(1899,11,30)+serial*86400000);return date.toISOString().slice(0,10);}const date=new Date(raw);return Number.isNaN(date.getTime())?'':date.toISOString().slice(0,10);}
function displayDate(value:string){const parts=value.split('-');return parts.length===3?`${parts[2]}/${parts[1]}/${parts[0]}`:value;}
function parseCsv(input:string):string[][]{const rows:string[][]=[];let row:string[]=[];let cell='';let quoted=false;for(let index=0;index<input.length;index++){const char=input[index];if(char==='"'){if(quoted&&input[index+1]==='"'){cell+='"';index++;}else{quoted=!quoted;}}else if(char===','&&!quoted){row.push(cell);cell='';}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&input[index+1]==='\n')index++;row.push(cell);if(row.some(value=>text(value)))rows.push(row);row=[];cell='';}else cell+=char;}if(cell||row.length){row.push(cell);if(row.some(value=>text(value)))rows.push(row);}return rows;}
function column(headers:string[],aliases:string[],fallback:number){const normalized=headers.map(norm);const index=normalized.findIndex(header=>aliases.some(alias=>header===norm(alias)||header.includes(norm(alias))));return index>=0?index:fallback;}
function calendarDays(from:string,to:string){if(!from||!to)return 0;const start=new Date(`${from}T00:00:00Z`);const end=new Date(`${to}T00:00:00Z`);const diff=Math.round((end.getTime()-start.getTime())/86400000);return diff>=0?diff+1:0;}
function sourceUrl(raw:string){const value=text(raw);if(!value)throw new Error('Chưa cấu hình đường link dữ liệu DỤNG CỤ.');if(!/^https:\/\//i.test(value))throw new Error('Nguồn DỤNG CỤ phải là đường link HTTPS của Google Sheet có quyền đọc.');const parsed=new URL(value);const host=parsed.hostname.toLowerCase();const allowed=host==='docs.google.com'||host==='drive.google.com'||host.endsWith('.googleusercontent.com');if(!allowed)throw new Error('Chỉ hỗ trợ nguồn Google Sheet HTTPS để bảo vệ máy chủ khỏi đường link ngoài hệ thống.');const match=parsed.pathname.match(/\/spreadsheets\/d\/([^/]+)/);if(!match)return parsed.toString();const gid=parsed.searchParams.get('gid')||parsed.hash.match(/gid=([\d-]+)/)?.[1]||'0';return `https://docs.google.com/spreadsheets/d/${encodeURIComponent(match[1])}/export?format=csv&gid=${encodeURIComponent(gid)}`;}

export async function loadCssdReport(config:AnyRecord,from:string,to:string){const reportUrl=text(config.cssdReportUrl||config.url);const sourceSheet=text(config.cssdSourceSheet)||'DỤNG CỤ BẬN';const targetPerDay=Math.max(0,Number(config.cssdTargetPerDay||0)||0);if(!reportUrl)return {ok:true,configured:false,sourceSheet,targetPerDay};const url=sourceUrl(reportUrl);const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),8000);try{const response=await fetch(url,{signal:controller.signal,headers:{accept:'text/csv,text/plain'}});if(!response.ok)throw new Error(`Nguồn dữ liệu trả về HTTP ${response.status}.`);const csv=await response.text();if(csv.length>5_000_000)throw new Error('Nguồn dữ liệu vượt quá 5 MB; hãy lọc hoặc rút gọn sheet nguồn.');const rows=parseCsv(csv);if(!rows.length)return {ok:true,configured:true,sourceSheet,targetPerDay,total:0,uniqueSets:0,activeDays:0,calendarDays:calendarDays(from,to),avgPerActiveDay:0,avgPerCalendarDay:0,peakDay:'',peakCount:0,utilizationPct:null,statusSummary:{DU:0,THIEU:0,HET_HAN:0,KHAC:0},daily:[],thieuList:[],hetHanList:[]};const headers=rows[0];const hasHeader=headers.some(value=>{const key=norm(value);return key.includes('ngay')||key.includes('trang thai')||key.includes('ten bo')||key.includes('bo dung cu');});const dataRows=(hasHeader?rows.slice(1):rows).slice(0,10000);const dateIndex=column(headers,['Ngày','Ngày ghi nhận','Ngày xử lý'],1);const setIndex=column(headers,['Tên bộ','Bộ dụng cụ','Tên bộ dụng cụ','Mã bộ'],3);const handoverIndex=column(headers,['Người giao'],5);const receiverIndex=column(headers,['Người nhận'],6);const statusIndex=column(headers,['Trạng thái'],7);const noteIndex=column(headers,['Ghi chú','Nội dung'],8);const statusSummary={DU:0,THIEU:0,HET_HAN:0,KHAC:0};const dailyMap=new Map<string,AnyRecord>();const setMap=new Set<string>();const thieuList:AnyRecord[]=[];const hetHanList:AnyRecord[]=[];let total=0;for(const row of dataRows){const date=ymd(row[dateIndex]);if(!date||from&&date<from||to&&date>to)continue;total++;const daily=dailyMap.get(date)||{date:displayDate(date),total:0,DU:0,THIEU:0,HET_HAN:0,KHAC:0};daily.total++;dailyMap.set(date,daily);const tenBo=text(row[setIndex]);if(tenBo)setMap.add(norm(tenBo));const item={date:displayDate(date),tenBo,nguoiGiao:text(row[handoverIndex]),nguoiNhan:text(row[receiverIndex]),ghiChu:text(row[noteIndex])};const status=norm(row[statusIndex]);if(status==='du'||status.includes(' du')){statusSummary.DU++;daily.DU++;}else if(status==='thieu'||status.includes('thieu')){statusSummary.THIEU++;daily.THIEU++;thieuList.push(item);}else if(status==='het han'||status.includes('het han')){statusSummary.HET_HAN++;daily.HET_HAN++;hetHanList.push(item);}else{statusSummary.KHAC++;daily.KHAC++;}}
 const daily=[...dailyMap.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([,value])=>value);const activeDays=daily.length;const days=calendarDays(from,to);const avgPerActiveDay=activeDays?Math.round(total*10/activeDays)/10:0;const avgPerCalendarDay=days?Math.round(total*10/days)/10:0;const peak=daily.reduce((best,item)=>Number(item.total)>Number(best.total)?item:best,{date:'',total:0});const utilizationPct=targetPerDay>0&&days>0?Math.round(total*1000/(targetPerDay*days))/10:null;return {ok:true,configured:true,sourceSheet,targetPerDay,total,uniqueSets:setMap.size,activeDays,calendarDays:days,avgPerActiveDay,avgPerCalendarDay,peakDay:peak.date,peakCount:peak.total,utilizationPct,statusSummary,daily,thieuList,hetHanList};
 }finally{clearTimeout(timeout);}}
