import {NextResponse} from 'next/server';
import {hasSession} from '../../../lib/auth';
import {supabaseAdmin} from '../../../lib/supabase';

export const runtime='nodejs';
export const dynamic='force-dynamic';

type AnyRecord=Record<string,any>;
type LegacyRow={row_no:number;legacy_id?:string|null;data:AnyRecord};
type Filters={from?:string;to?:string;department?:string;person?:string;title?:string;priority?:string;status?:string;assignees?:string[];statuses?:string[];formCode?:string;type?:string};

const PAGE=1000;
const BASE_DEPARTMENTS=['VỆ SINH MÔI TRƯỜNG','ĐỒ VẢI','GIÁM SÁT','DỤNG CỤ','VI PHẠM CHUNG'];
const TASK_PRIORITIES=['CHẬM','TRUNG BÌNH','NHANH','HOÀN THÀNH','TRONG TUẦN'];
const TASK_STATUSES=['CHƯA BẮT ĐẦU','ĐANG LÀM','ĐÃ HOÀN THÀNH','QUÁ HẠN'];
const TASK_EVAL_STATUSES=['CHƯA BẮT ĐẦU','XUẤT SẮC','TỐT','KHÁ','CHƯA ĐẠT_LÀM LẠI','KÉM','QUÁ HẠN'];
const S={
 staff:'DM_NHANVIEN',tasks:'GIAO VIỆC',reminders:'NHAC_VIEC_GHI_CHU',
 violations:'THEODOI_VIPHAM',errors:'DM_LOI',violationSummary:'TONG_HOP_VI_PHAM',
 checklists:'PHIEU_GIAMSAT',checklistDetails:'CT_PHIEU_GIAMSAT',checklistForms:'DM_PHIEU_GIAMSAT',
 checklistCriteria:'DM_BANGKIEM',checklistConfig:'DM_CAUHINH_PHIEU',
 weekly:'KE_HOACH_TUAN',monthly:'KE_HOACH_THANG',issues:'TON_TAI_KIEN_NGHI',
 opinions:'Y_KIEN_BAO_CAO',kpi:'KPI_100_DIEM',kpiRules:'DM_QUYDOI_KPI',kpiFeedback:'Y_KIEN_KPI'
} as const;
const DONE=['hoan thanh','da hoan thanh','dong','da khac phuc','hoan tat','da xong'];
const TASK_SCORE:AnyRecord={'XUẤT SẮC':10,'TỐT':5,'KHÁ':0,'CHƯA ĐẠT':-5,'CHƯA ĐẠT_LÀM LẠI':-5,'LÀM LẠI':-5,'KÉM':-10,'QUÁ HẠN':-5};
const DEFAULT_RULES=([
 {order:1,ranking:'XUẤT SẮC',min:110,max:999999,color:'#2563EB'},
 {order:2,ranking:'TỐT',min:95,max:109.99,color:'#16A34A'},
 {order:3,ranking:'KHÁ',min:80,max:94.99,color:'#0891B2'},
 {order:4,ranking:'TRUNG BÌNH',min:65,max:79.99,color:'#F59E0B'},
 {order:5,ranking:'CHƯA ĐẠT',min:-999999,max:64.99,color:'#DC2626'}
]);

function db(){const client=supabaseAdmin();if(!client)throw new Error('SUPABASE_SERVICE_ROLE_KEY chưa cấu hình');return client;}
function text(value:unknown){return value==null?'':String(value).trim();}
function norm(value:unknown){return text(value).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/\s+/g,' ');}
function same(a:unknown,b:unknown){return norm(a)===norm(b);}
function pick(data:AnyRecord,keys:string[]){for(const key of keys){if(data[key]!=null&&text(data[key]))return text(data[key]);}return '';}
function num(value:unknown){const n=Number(String(value??'').replace(',','.'));return Number.isFinite(n)?n:0;}
function ymd(value:unknown){
 const raw=text(value);if(!raw)return '';
 const iso=raw.match(/(\d{4}-\d{2}-\d{2})/);if(iso)return iso[1];
 const dmy=raw.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/);if(dmy)return `${dmy[3]}-${String(dmy[2]).padStart(2,'0')}-${String(dmy[1]).padStart(2,'0')}`;
 if(typeof value==='number'&&value>20000&&value<80000){const d=new Date(Date.UTC(1899,11,30)+value*86400000);return d.toISOString().slice(0,10);}
 const d=new Date(raw);return Number.isNaN(d.getTime())?'':d.toISOString().slice(0,10);
}
function today(){const d=new Date();return d.toISOString().slice(0,10);}
function done(value:unknown){const valueNorm=norm(value);return DONE.some(word=>valueNorm.includes(word));}
function dayDelta(value:unknown){const raw=ymd(value);if(!raw)return null;const target=new Date(`${raw}T00:00:00`);const current=new Date(`${today()}T00:00:00`);return Math.round((target.getTime()-current.getTime())/86400000);}
function alertLevel(value:unknown){const delta=dayDelta(value);if(delta===null||delta>7)return '';if(delta<0)return 'QUÁ HẠN';if(delta===0)return 'HÔM NAY';if(delta<=3)return '1–3 NGÀY';return '4–7 NGÀY';}
function overlap(startValue:unknown,endValue:unknown,filters:Filters){const start=ymd(startValue);const end=ymd(endValue)||start;if(!filters.from&&!filters.to)return true;return (!end||end>=(filters.from||'0000-01-01'))&&(!start||start<=(filters.to||'9999-12-31'));}
function inRange(value:unknown,filters:Filters){const date=ymd(value);return (!filters.from||!date||date>=filters.from)&&(!filters.to||!date||date<=filters.to);}
function arrayParam(url:URL,name:string){const raw=url.searchParams.get(name);if(!raw)return [];try{const parsed=JSON.parse(raw);return Array.isArray(parsed)?parsed.map(text).filter(Boolean):[];}catch{return raw.split('|').map(text).filter(Boolean);}}
function parseFilters(url:URL):Filters{return {from:text(url.searchParams.get('from')),to:text(url.searchParams.get('to')),department:text(url.searchParams.get('department')),person:text(url.searchParams.get('person')),title:text(url.searchParams.get('title')),priority:text(url.searchParams.get('priority')),status:text(url.searchParams.get('status')),assignees:arrayParam(url,'assignees'),statuses:arrayParam(url,'statuses'),formCode:text(url.searchParams.get('formCode')),type:text(url.searchParams.get('type'))};}

async function readSheet(sheet:string):Promise<LegacyRow[]>{
 const client=db();const rows:LegacyRow[]=[];let from=0;
 while(true){const {data,error}=await client.from('ksnk_legacy_rows').select('row_no,legacy_id,data').eq('sheet_name',sheet).order('row_no',{ascending:true}).range(from,from+PAGE-1);if(error)throw error;const part=(data||[]) as LegacyRow[];rows.push(...part);if(part.length<PAGE)break;from+=PAGE;}
 return rows;
}
async function readRow(sheet:string,rowNo:number){const {data,error}=await db().from('ksnk_legacy_rows').select('row_no,legacy_id,data').eq('sheet_name',sheet).eq('row_no',rowNo).maybeSingle();if(error)throw error;return data as LegacyRow|null;}
async function nextRowNo(sheet:string){const {data,error}=await db().from('ksnk_legacy_rows').select('row_no').eq('sheet_name',sheet).order('row_no',{ascending:false}).limit(1);if(error)throw error;return Number(data?.[0]?.row_no||0)+1;}
async function saveRow(sheet:string,rowNo:number|undefined,data:AnyRecord){
 const client=db();const n=rowNo&&rowNo>0?rowNo:await nextRowNo(sheet);const old=rowNo&&rowNo>0?await readRow(sheet,rowNo):null;const merged={...(old?.data||{}),...data};
 const legacy=text(merged.ID||merged['Mã công việc']||merged['Mã NV']||merged['Mã VP']||merged['Mã phiếu']||merged['Mã KH']||merged['Mã TT']||merged['MÃ NHẮC VIỆC']||old?.legacy_id||`${sheet}:${n}`);
 const {error}=await client.from('ksnk_legacy_rows').upsert({sheet_name:sheet,row_no:n,legacy_id:legacy,data:merged},{onConflict:'sheet_name,row_no'});if(error)throw error;return n;
}
async function deleteRow(sheet:string,rowNo:number){if(!sheet||!rowNo)throw new Error('Thiếu bản ghi cần xóa');const {error}=await db().from('ksnk_legacy_rows').delete().eq('sheet_name',sheet).eq('row_no',rowNo);if(error)throw error;}
function rowData(row:LegacyRow){return {row_no:row.row_no,legacy_id:row.legacy_id||'',data:row.data};}

function getStaff(rows:LegacyRow[]){return rows.map(row=>{const d=row.data;return {row_no:row.row_no,legacy_id:row.legacy_id||'',id:pick(d,['Mã NV']),name:pick(d,['Họ và tên','Họ tên']),department:pick(d,['Bộ phận']),position:pick(d,['Chức vụ']),phone:pick(d,['Số điện thoại']),status:pick(d,['Trạng thái']),data:d};}).filter(x=>x.name);}
function staffMap(staff:AnyRecord[]){return new Map<string,string>(staff.map(x=>[norm(x.name),text(x.department)] as [string,string]));}
function task(row:LegacyRow,map?:Map<string,string>){const d=row.data;const assignee=pick(d,['Người thực hiện','Người chịu trách nhiệm']);const savedStatus=pick(d,['Trạng thái NV','Trạng thái'])||'CHƯA BẮT ĐẦU';const savedEvalStatus=pick(d,['Đánh giá quản lý','Đánh giá'])||'CHƯA BẮT ĐẦU';const startDate=ymd(d['Ngày bắt đầu']);const endDate=ymd(d['Ngày kết thúc']);const overdue=Boolean(endDate&&endDate<today()&&!done(savedStatus));const status=overdue?'QUÁ HẠN':savedStatus;const evalStatus=overdue&&!['XUẤT SẮC','TỐT','KHÁ','QUÁ HẠN'].includes(savedEvalStatus)?'QUÁ HẠN':savedEvalStatus;return {row_no:row.row_no,legacy_id:row.legacy_id||'',id:pick(d,['ID','Mã công việc']),taskId:pick(d,['ID','Mã công việc']),assignee,department:pick(d,['Bộ phận','Thuộc bộ phận'])||map?.get(norm(assignee))||'',assigner:pick(d,['Người giao việc','Người giao','Người tạo']),priority:pick(d,['Mức độ ưu tiên','Mức ưu tiên'])||'TRUNG BÌNH',title:pick(d,['Tiêu đề công việc','Tiêu đề']),description:pick(d,['Nội dung / Mô tả','Nội dung','Mô tả']),startDate,endDate,status,savedStatus,note:pick(d,['Ghi chú NV','Ghi chú']),imageName:pick(d,['Ảnh minh chứng']),evalStatus,savedEvalStatus,qlNote:pick(d,['Ghi chú quản lý','Ghi chú / Phản hồi quản lý']),managerOpinion:pick(d,['Ý kiến quản lý','Ý kiến của quản lý','Ý kiến trưởng khoa']),data:d};}
function reminder(row:LegacyRow){const d=row.data;return {row_no:row.row_no,legacy_id:row.legacy_id||'',id:pick(d,['MÃ NHẮC VIỆC','Mã nhắc việc']),reminderId:pick(d,['MÃ NHẮC VIỆC','Mã nhắc việc']),date:ymd(d['NGÀY NHẮC']??d['Ngày nhắc']),title:pick(d,['TIÊU ĐỀ NHẮC VIỆC','Tiêu đề nhắc việc']),note:pick(d,['NỘI DUNG / GHI CHÚ','Nội dung / Ghi chú','Ghi chú']),person:pick(d,['NGƯỜI LIÊN QUAN','Người liên quan']),status:pick(d,['TRẠNG THÁI','Trạng thái'])||'CHƯA THỰC HIỆN',data:d};}
function violation(row:LegacyRow){const d=row.data;const person=pick(d,['Họ tên','Họ và tên']);return {row_no:row.row_no,legacy_id:row.legacy_id||'',id:pick(d,['Mã VP','Mã vi phạm','ID']),date:ymd(d['Ngày vi phạm']),staffId:pick(d,['Mã NV']),person,name:person,department:pick(d,['Bộ phận']),errorId:pick(d,['Mã lỗi']),errorName:pick(d,['Tên lỗi']),level:pick(d,['Mức độ']),score:num(d['Điểm trừ']),points:num(d['Điểm trừ']),recorder:pick(d,['Người ghi nhận']),note:pick(d,['Ghi chú']),status:pick(d,['Trạng thái'])||'Chưa xử lý',imageName:pick(d,['Hình ảnh','Ảnh minh chứng']),data:d};}
function plan(row:LegacyRow,type:string){const d=row.data;const saved=pick(d,['Trạng thái'])||'CHƯA BẮT ĐẦU';const toDate=ymd(d['Đến ngày']);const status=!done(saved)&&toDate&&toDate<today()?'QUÁ HẠN':saved;return {row_no:row.row_no,legacy_id:row.legacy_id||'',id:pick(d,['Mã KH','ID']),type,fromDate:ymd(d['Từ ngày']),toDate,department:pick(d,['Bộ phận']),content:pick(d,['Nội dung']),description:pick(d,['Nội dung / Mô tả','Mô tả']),owner:pick(d,['Người phụ trách']),status,savedStatus:saved,result:pick(d,['Kết quả']),note:pick(d,['Ghi chú']),completedAt:ymd(d['Ngày hoàn thành']),rootId:pick(d,['Mã kế hoạch gốc']),carryPeriod:pick(d,['Kỳ chuyển tiếp']),data:d};}
function issue(row:LegacyRow,map?:Map<string,string>){const d=row.data;const owner=pick(d,['Người phụ trách']);return {row_no:row.row_no,legacy_id:row.legacy_id||'',id:pick(d,['Mã TT','ID']),date:ymd(d['Ngày ghi nhận']??d['Ngày']),department:pick(d,['Bộ phận'])||map?.get(norm(owner))||'',issue:pick(d,['Tồn tại / Sự cố / Kiến nghị','Nội dung']),cause:pick(d,['Nguyên nhân']),action:pick(d,['Phương án khắc phục']),owner,deadline:ymd(d['Hạn xử lý']??d['Hạn']),status:pick(d,['Trạng thái'])||'CHƯA KHẮC PHỤC',recommendation:pick(d,['Kiến nghị']),note:pick(d,['Ghi chú']),kind:pick(d,['Loại nội dung','Loại']),data:d};}
function opinion(row:LegacyRow){const d=row.data;return {row_no:row.row_no,legacy_id:row.legacy_id||'',opinionId:pick(d,['Mã ý kiến','Mã ý kiến báo cáo','ID']),fromDate:ymd(d['Từ ngày']),toDate:ymd(d['Đến ngày']),department:pick(d,['Bộ phận']),person:pick(d,['Nhân viên']),reportId:pick(d,['Mã phiếu','Mã báo cáo']),formCode:pick(d,['Mã phiếu']),formName:pick(d,['Tên phiếu']),opinion:pick(d,['Ý kiến khắc phục của tổ trưởng','Ý kiến','Nội dung góp ý','Ghi chú']),enteredBy:pick(d,['Người nhập','Người thực hiện']),status:pick(d,['Trạng thái'])||'Đã lưu',data:d};}
function checklist(row:LegacyRow){const d=row.data;return {row_no:row.row_no,legacy_id:row.legacy_id||'',id:pick(d,['Mã phiếu','ID']),date:ymd(d['Ngày giám sát']??d['Ngày']),staffId:pick(d,['Mã NV']),person:pick(d,['Họ tên','Họ và tên']),name:pick(d,['Họ tên','Họ và tên']),department:pick(d,['Bộ phận']),supervisor:pick(d,['Người giám sát']),area:pick(d,['Khu vực']),shift:pick(d,['Ca']),formCode:pick(d,['Mã mẫu phiếu','Mã phiếu']),formName:pick(d,['Tên phiếu']),applied:num(d['Tổng áp dụng']),pass:num(d['Đạt']),fail:num(d['Không đạt']),rate:num(d['Tỷ lệ %']),kpi:num(d['Điểm KPI']??d['KPI bảng kiểm áp dụng']),note:pick(d,['Ghi chú']),imageName:pick(d,['Ảnh minh chứng','Hình ảnh']),na:num(d['Không áp dụng']),data:d};}
function formMaster(row:LegacyRow){const d=row.data;return {row_no:row.row_no,legacy_id:row.legacy_id||'',code:pick(d,['Mã phiếu','Mã mẫu phiếu']),name:pick(d,['Tên phiếu','Tên mẫu phiếu']),department:pick(d,['Bộ phận']),description:pick(d,['Mô tả','Nội dung']),criteriaCount:pick(d,['Số tiêu chí']),status:pick(d,['Trạng thái'])||'Hoạt động',data:d};}
function criterion(row:LegacyRow){const d=row.data;return {row_no:row.row_no,legacy_id:row.legacy_id||'',id:pick(d,['Mã tiêu chí','ID']),formCode:pick(d,['Mã phiếu','Mã mẫu phiếu']),department:pick(d,['Bộ phận']),group:pick(d,['Nhóm tiêu chí','Nhóm']),content:pick(d,['Nội dung tiêu chí','Nội dung']),detail:pick(d,['Nội dung chi tiết','Chi tiết']),order:pick(d,['STT','Thứ tự']),allowImage:pick(d,['Cho phép hình ảnh','Cho phép ảnh'])||'Có',status:pick(d,['Trạng thái'])||'Hoạt động',data:d};}

function taskFilter(rows:AnyRecord[],f:Filters){const title=norm(f.title);return rows.filter(x=>overlap(x.startDate,x.endDate,f)&&(!f.department||same(x.department,f.department))&&(!f.person||same(x.assignee,f.person))&&(!f.assignees?.length||f.assignees.some(y=>same(y,x.assignee)))&&(!f.priority||same(x.priority,f.priority))&&(!f.status||same(x.status,f.status))&&(!f.statuses?.length||f.statuses.some(y=>same(y,x.status)))&&(!title||norm(x.title).includes(title)));}
async function persistOverdueTasks(rows:LegacyRow[],mapped:AnyRecord[]){const updates=rows.map((row,index)=>{const item=mapped[index];if(!item||item.status===item.savedStatus&&item.evalStatus===item.savedEvalStatus)return null;return {sheet_name:S.tasks,row_no:row.row_no,legacy_id:row.legacy_id||item.id||`${S.tasks}:${row.row_no}`,data:{...row.data,'Trạng thái NV':item.status,'Đánh giá quản lý':item.evalStatus}};}).filter(Boolean) as AnyRecord[];if(!updates.length)return;const {error}=await db().from('ksnk_legacy_rows').upsert(updates,{onConflict:'sheet_name,row_no'});if(error)throw error;}
function reminderFilter(rows:AnyRecord[],f:Filters){const title=norm(f.title);return rows.filter(x=>inRange(x.date,f)&&(!f.person||same(x.person,f.person))&&(!f.status||same(x.status,f.status))&&(!title||norm(x.title).includes(title)));}
function performance(rows:AnyRecord[],staff:AnyRecord[]){const names=[...new Set([...staff.map(x=>x.name),...rows.map(x=>x.assignee).filter(Boolean)])].filter(Boolean);return names.map(name=>{const mine=rows.filter(x=>same(x.assignee,name));const score={excellent:mine.filter(x=>norm(x.evalStatus)==='xuat sac').length,good:mine.filter(x=>norm(x.evalStatus)==='tot').length,fair:mine.filter(x=>norm(x.evalStatus)==='kha').length,poor:mine.filter(x=>norm(x.evalStatus).includes('chua dat')||norm(x.evalStatus)==='lam lai').length,bad:mine.filter(x=>norm(x.evalStatus)==='kem').length};const total=100+score.excellent*10+score.good*5-score.poor*5-score.bad*10;const rank=total>=110?'XUẤT SẮC':total>=95?'TỐT':total>=80?'KHÁ':total>=65?'TRUNG BÌNH':'CHƯA ĐẠT';return {name,totalTasks:mine.length,completed:mine.filter(x=>done(x.status)).length,overdue:mine.filter(x=>norm(x.status).includes('qua han')||(!done(x.status)&&x.endDate<today())).length,...score,total,rank};});}
function rulesFrom(rows:AnyRecord[]){const rules=rows.map(row=>{const d=row.data||row;return {row_no:row.row_no,order:num(d['STT']??row.order),ranking:pick(d,['Xếp loại'])||text(row.ranking),min:num(d['Từ điểm']??row.min),max:num(d['Đến điểm']??row.max),color:pick(d,['Màu'])||row.color||'#6C757D',status:pick(d,['Trạng thái'])||'Hoạt động'};}).filter(x=>x.ranking&&norm(x.status)!=='tam ngung'&&norm(x.status)!=='ngung').sort((a,b)=>a.order-b.order);return rules.length?rules:DEFAULT_RULES;}
function rankFor(total:number,rules:AnyRecord[]){return rules.find(x=>total>=x.min&&total<=x.max)||rules[rules.length-1]||DEFAULT_RULES[DEFAULT_RULES.length-1];}
function computeKpi(staff:AnyRecord[],tasks:AnyRecord[],checks:AnyRecord[],violations:AnyRecord[],rules:AnyRecord[]){return staff.map(s=>{const st=tasks.filter(x=>same(x.assignee,s.name));const sc=checks.filter(x=>same(x.person,s.name));const sv=violations.filter(x=>same(x.person,s.name));let taskScore=0;const details:string[]=[];for(const x of st){const key=text(x.evalStatus).toUpperCase();const value=Number(TASK_SCORE[key]??0);taskScore+=value;if(value)details.push(`${value>0?'+':''}${value} Giao việc: ${x.title} (${key})`);}const checklistScore=sc.reduce((n,x)=>n+num(x.kpi),0);for(const x of sc){if(num(x.kpi))details.push(`${x.kpi} Bảng kiểm ${x.date}: ${x.rate}%`);}const violationScore=-sv.reduce((n,x)=>n+Math.abs(num(x.points)),0);for(const x of sv){if(num(x.points))details.push(`-${Math.abs(num(x.points))} Vi phạm ${x.date}: ${x.errorName}`);}const total=100+taskScore+checklistScore+violationScore;const rank=rankFor(total,rules);return {staffId:s.id,name:s.name,person:s.name,department:s.department,position:s.position,base:100,taskScore,checklistScore,violationScore,total,ranking:rank.ranking,rank:rank.ranking,rankingColor:rank.color,details,taskCount:st.length,checkCount:sc.length,violationCount:sv.length};});}

async function buildModule(moduleName:string,f:Filters){
 const staff=getStaff(await readSheet(S.staff));const departments=[...new Set([...BASE_DEPARTMENTS,...staff.map(x=>x.department).filter(Boolean)])].sort((a,b)=>a.localeCompare(b,'vi'));const map=staffMap(staff);
 if(moduleName==='staff'){const rows=staff.filter(x=>(!f.department||same(x.department,f.department))&&(!f.person||norm(x.name).includes(norm(f.person))));return {rows,total:rows.length,departments,staff};}
 if(moduleName==='tasks'){const [taskRows,reminderRows]=await Promise.all([readSheet(S.tasks),readSheet(S.reminders)]);const all=taskRows.map(x=>task(x,map));await persistOverdueTasks(taskRows,all);const rows=taskFilter(all,f);const reminders=reminderFilter(reminderRows.map(reminder),f);return {rows,total:rows.length,reminders,reminderTotal:reminders.length,staff,departments,options:{priorities:[...new Set([...TASK_PRIORITIES,...all.map(x=>x.priority).filter(Boolean)])].sort(),statuses:[...new Set([...TASK_STATUSES,...all.map(x=>x.status).filter(Boolean)])].sort(),evalStatuses:[...new Set([...TASK_EVAL_STATUSES,...all.map(x=>x.evalStatus).filter(Boolean)])].sort(),reminderStatuses:[...new Set(reminderRows.map(x=>reminder(x).status).filter(Boolean))].sort(),assignees:[...new Set(staff.map(x=>x.name).filter(Boolean))]},performance:performance(rows,staff)};}
 if(moduleName==='reminders'){const rows=reminderFilter((await readSheet(S.reminders)).map(reminder),f);return {rows,total:rows.length,staff,departments,options:{statuses:[...new Set(rows.map(x=>x.status).filter(Boolean))].sort()}};}
 if(moduleName==='violations'){const [source,errorRows,summaryRows]=await Promise.all([readSheet(S.violations),readSheet(S.errors),readSheet(S.violationSummary)]);const rows=source.map(violation).filter(x=>inRange(x.date,f)&&(!f.department||same(x.department,f.department))&&(!f.person||same(x.person,f.person)));const errorCatalog=errorRows.map(r=>{const d=r.data;return {row_no:r.row_no,id:pick(d,['Mã lỗi']),name:pick(d,['Tên lỗi']),department:pick(d,['Bộ phận']),level:pick(d,['Mức độ']),score:num(d['Điểm trừ']),note:pick(d,['Ghi chú']),status:pick(d,['Trạng thái']),data:d};});return {rows,total:rows.length,errors:errorRows.map(rowData),errorCatalog,monthlySummary:summaryRows.map(rowData),summary:staff.map(s=>({name:s.name,department:s.department,score:rows.filter(x=>same(x.person,s.name)).reduce((n,x)=>n+num(x.score),0)})).filter(x=>x.score>0),staff,departments};}
 if(moduleName==='checklists'){const [history,formRows,criterionRows,detailRows,configRows]=await Promise.all([readSheet(S.checklists),readSheet(S.checklistForms),readSheet(S.checklistCriteria),readSheet(S.checklistDetails),readSheet(S.checklistConfig)]);const rows=history.map(checklist).filter(x=>inRange(x.date,f)&&(!f.department||same(x.department,f.department))&&(!f.person||same(x.person,f.person))&&(!f.formCode||same(x.formCode,f.formCode)));return {rows,total:rows.length,forms:formRows.map(formMaster),criteria:criterionRows.map(criterion),details:detailRows.map(rowData),percentConfig:configRows.map(rowData),staff,departments,summary:{total:rows.length,pass:rows.reduce((n,x)=>n+num(x.pass),0),fail:rows.reduce((n,x)=>n+num(x.fail),0),averageRate:rows.length?Math.round(rows.reduce((n,x)=>n+num(x.rate),0)/rows.length*100)/100:0}};}
 if(moduleName==='plans'){const [week,month,issueRows]=await Promise.all([readSheet(S.weekly),readSheet(S.monthly),readSheet(S.issues)]);const rows=[...week.map(x=>plan(x,'TUẦN')),...month.map(x=>plan(x,'THÁNG'))].filter(x=>(!f.type||x.type===f.type)&&overlap(x.fromDate,x.toDate,f)&&(!f.department||same(x.department,f.department))&&(!f.person||same(x.owner,f.person))&&(!f.status||same(x.status,f.status)));const issues=issueRows.map(x=>issue(x,map)).filter(x=>inRange(x.date,f)&&(!f.department||same(x.department,f.department))&&(!f.person||same(x.owner,f.person)));return {rows,total:rows.length,issues,staff,departments,summary:{total:rows.length,done:rows.filter(x=>done(x.status)).length,overdue:rows.filter(x=>norm(x.status)==='qua han').length,openIssues:issues.filter(x=>!done(x.status)).length},options:{statuses:[...new Set([...rows.map(x=>x.status),'CHƯA BẮT ĐẦU','ĐANG THỰC HIỆN','HOÀN THÀNH','QUÁ HẠN','CHUYỂN TIẾP'].filter(Boolean))],issueStatuses:['CHƯA KHẮC PHỤC','ĐANG XỬ LÝ','ĐÃ KHẮC PHỤC','QUÁ HẠN']}};}
 if(moduleName==='reports')return buildReports(f,staff,departments,map);
 if(moduleName==='kpi')return buildKpi(f,staff,departments,map);
 if(moduleName==='alerts')return buildAlerts(f,staff,departments,map);
 const raw=await readSheet(moduleName);return {rows:raw.map(rowData),total:raw.length,departments,staff};
}

async function buildReports(f:Filters,staff:AnyRecord[],departments:string[],map:Map<string,string>){
 const [taskRows,violationRows,checkRows,weekRows,monthRows,issueRows,opinionRows]=await Promise.all([readSheet(S.tasks),readSheet(S.violations),readSheet(S.checklists),readSheet(S.weekly),readSheet(S.monthly),readSheet(S.issues),readSheet(S.opinions)]);
 const tasks=taskFilter(taskRows.map(x=>task(x,map)),f);const violations=violationRows.map(violation).filter(x=>inRange(x.date,f)&&(!f.department||same(x.department,f.department))&&(!f.person||same(x.person,f.person)));const checks=checkRows.map(checklist).filter(x=>inRange(x.date,f)&&(!f.department||same(x.department,f.department))&&(!f.person||same(x.person,f.person)));const plans=[...weekRows.map(x=>plan(x,'TUẦN')),...monthRows.map(x=>plan(x,'THÁNG'))].filter(x=>overlap(x.fromDate,x.toDate,f)&&(!f.department||same(x.department,f.department))&&(!f.person||same(x.owner,f.person)));const issues=issueRows.map(x=>issue(x,map)).filter(x=>inRange(x.date,f)&&(!f.department||same(x.department,f.department)));
 const deps=[...new Set([...departments,...tasks.map(x=>x.department),...violations.map(x=>x.department),...checks.map(x=>x.department),...plans.map(x=>x.department),...issues.map(x=>x.department)].filter(Boolean))].filter(x=>!f.department||same(x,f.department)).sort((a,b)=>a.localeCompare(b,'vi'));
 const rows=deps.map(department=>{const t=tasks.filter(x=>same(x.department,department));const v=violations.filter(x=>same(x.department,department));const c=checks.filter(x=>same(x.department,department));const p=plans.filter(x=>same(x.department,department));const i=issues.filter(x=>same(x.department,department));return {department,taskCount:t.length,completedTasks:t.filter(x=>done(x.status)).length,overdueTasks:t.filter(x=>norm(x.status).includes('qua han')||(!done(x.status)&&x.endDate<today())).length,violationCount:v.length,violationPoints:v.reduce((n,x)=>n+Math.abs(num(x.points)),0),checklistCount:c.length,checklistRate:c.length?Math.round(c.reduce((n,x)=>n+num(x.rate),0)/c.length*100)/100:0,checklistFails:c.reduce((n,x)=>n+num(x.fail),0),planCount:p.length,openPlans:p.filter(x=>!done(x.status)).length,issueCount:i.length};});
 const errors=new Map<string,AnyRecord>();for(const x of violations){const key=x.errorName||'Chưa phân loại';const item=errors.get(key)||{errorName:key,count:0,totalPoints:0};item.count++;item.totalPoints+=Math.abs(num(x.points));errors.set(key,item);}
 return {rows,total:rows.length,departments,staff,totals:{tasks:tasks.length,taskDone:tasks.filter(x=>done(x.status)).length,violations:violations.length,violationPoints:violations.reduce((n,x)=>n+Math.abs(num(x.points)),0),checklists:checks.length,checklistFails:checks.reduce((n,x)=>n+num(x.fail),0),plans:plans.length,plansDone:plans.filter(x=>done(x.status)).length,issues:issues.length},tasks,plans,checks,violations,issues,opinions:opinionRows.map(opinion),special:{errorStats:[...errors.values()].sort((a,b)=>b.count-a.count),failures:checks.filter(x=>num(x.fail)>0),conclusion:violations.length?`Ghi nhận ${violations.length} vi phạm, tổng ${violations.reduce((n,x)=>n+Math.abs(num(x.points)),0)} điểm trừ.`:'Không ghi nhận vi phạm trong kỳ báo cáo.'}};
}

async function buildKpi(f:Filters,staff:AnyRecord[],departments:string[],map:Map<string,string>){
 const [taskRows,checkRows,violationRows,storedRows,ruleRows,feedbackRows]=await Promise.all([readSheet(S.tasks),readSheet(S.checklists),readSheet(S.violations),readSheet(S.kpi),readSheet(S.kpiRules),readSheet(S.kpiFeedback)]);
 const tasks=taskFilter(taskRows.map(x=>task(x,map)),{...f,person:''});const checks=checkRows.map(checklist).filter(x=>inRange(x.date,f)&&(!f.department||same(x.department,f.department))&&(!f.person||norm(x.person).includes(norm(f.person))));const violations=violationRows.map(violation).filter(x=>inRange(x.date,f)&&(!f.department||same(x.department,f.department))&&(!f.person||norm(x.person).includes(norm(f.person))));const scopedStaff=staff.filter(x=>(!f.department||same(x.department,f.department))&&(!f.person||norm(x.name).includes(norm(f.person))));const rules=rulesFrom(ruleRows.map(rowData));const rows=computeKpi(scopedStaff,tasks,checks,violations,rules);const stored=storedRows.map(row=>{const d=row.data;return {row_no:row.row_no,legacy_id:row.legacy_id||'',date:ymd(d['Thời gian lưu']),fromDate:ymd(d['Từ ngày']),toDate:ymd(d['Đến ngày']),staffId:pick(d,['Mã NV']),person:pick(d,['Họ tên','Nhân viên']),department:pick(d,['Bộ phận']),position:pick(d,['Chức vụ']),base:num(d['Điểm gốc']),taskScore:num(d['Điểm giao việc']),checklistScore:num(d['Điểm bảng kiểm']),violationScore:num(d['Điểm vi phạm']),total:num(d['Tổng điểm']),rank:pick(d,['Xếp loại']),detail:pick(d,['Chi tiết']),data:d};}).filter(x=>(!f.from||!x.fromDate||x.fromDate>=f.from)&&(!f.to||!x.toDate||x.toDate<=f.to));const rankCounts=rules.reduce((out,rule)=>{out[rule.ranking]=rows.filter(x=>x.ranking===rule.ranking).length;return out;},{} as AnyRecord);const summary={staffCount:rows.length,totalScore:rows.reduce((n,x)=>n+x.total,0),averageScore:rows.length?Math.round(rows.reduce((n,x)=>n+x.total,0)/rows.length*10)/10:0,totalTaskScore:rows.reduce((n,x)=>n+x.taskScore,0),totalChecklistScore:rows.reduce((n,x)=>n+x.checklistScore,0),totalViolationScore:rows.reduce((n,x)=>n+x.violationScore,0),rankCounts};return {rows,total:rows.length,stored,departments,staff,rules,conversionRules:rules,feedback:feedbackRows.map(rowData),summary,conclusion:rows.length?`Điểm KPI bình quân của ${rows.length} nhân viên: ${summary.averageScore.toFixed(1)} điểm.`:'Không có dữ liệu KPI phù hợp với bộ lọc hiện tại.'};
}

async function buildAlerts(f:Filters,staff:AnyRecord,departments:string[],map:Map<string,string>){
 const [taskRows,weekRows,monthRows,reminderRows]=await Promise.all([readSheet(S.tasks),readSheet(S.weekly),readSheet(S.monthly),readSheet(S.reminders)]);const alerts:AnyRecord[]=[];
 for(const x of taskRows.map(row=>task(row,map))){const level=alertLevel(x.endDate);if(level&&!done(x.status)&&(!f.department||same(x.department,f.department))&&(!f.person||same(x.assignee,f.person)))alerts.push({kind:'GIAO VIỆC',level,date:x.endDate,title:x.title,person:x.assignee,department:x.department,target:'tasks',row_no:x.row_no,id:x.id});}
 for(const x of [...weekRows.map(row=>plan(row,'TUẦN')),...monthRows.map(row=>plan(row,'THÁNG'))]){const level=alertLevel(x.toDate);if(level&&!done(x.status)&&(!f.department||same(x.department,f.department))&&(!f.person||same(x.owner,f.person)))alerts.push({kind:x.type==='TUẦN'?'KẾ HOẠCH TUẦN':'KẾ HOẠCH THÁNG',level,date:x.toDate,title:x.content,person:x.owner,department:x.department,target:'plans',row_no:x.row_no,id:x.id,type:x.type});}
 for(const x of reminderRows.map(reminder)){const level=alertLevel(x.date)||'NHẮC';if(!done(x.status)&&(!f.person||same(x.person,f.person)))alerts.push({kind:'NHẮC VIỆC',level,date:x.date,title:x.title,person:x.person,department:'',target:'reminders',row_no:x.row_no,id:x.id});}
 return {rows:alerts.sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))),total:alerts.length,departments,staff};
}

function canonical(moduleName:string,body:AnyRecord){const data=body.data&&typeof body.data==='object'&&!Array.isArray(body.data)?body.data:{};
 if(moduleName==='staff')return {'Mã NV':body.id??data['Mã NV']??'','Họ và tên':body.name??data['Họ và tên']??'','Bộ phận':body.department??data['Bộ phận']??'','Chức vụ':body.position??data['Chức vụ']??'','Số điện thoại':body.phone??data['Số điện thoại']??'','Trạng thái':body.status??data['Trạng thái']??'Đang làm việc'};
 if(moduleName==='tasks')return {'ID':text(body.taskId??data.ID??'')||`CV${Date.now()}`,'Người thực hiện':body.assignee??data['Người thực hiện']??'','Bộ phận':body.department??data['Bộ phận']??data['Thuộc bộ phận']??'','Thuộc bộ phận':body.department??data['Thuộc bộ phận']??data['Bộ phận']??'','Người giao việc':body.assigner??data['Người giao việc']??data['Người giao']??data['Người tạo']??'','Mức độ ưu tiên':body.priority??data['Mức độ ưu tiên']??'TRUNG BÌNH','Tiêu đề công việc':body.title??data['Tiêu đề công việc']??'','Nội dung / Mô tả':body.description??data['Nội dung / Mô tả']??'','Ngày bắt đầu':body.startDate??data['Ngày bắt đầu']??'','Ngày kết thúc':body.endDate??data['Ngày kết thúc']??'','Trạng thái NV':body.status??data['Trạng thái NV']??'CHƯA BẮT ĐẦU','Ghi chú NV':body.note??data['Ghi chú NV']??'','Ảnh minh chứng':body.imageName??data['Ảnh minh chứng']??'','Đánh giá quản lý':body.evalStatus??data['Đánh giá quản lý']??'CHƯA BẮT ĐẦU','Ghi chú quản lý':body.qlNote??data['Ghi chú quản lý']??'','Ý kiến quản lý':body.managerOpinion??data['Ý kiến quản lý']??data['Ý kiến của quản lý']??''};
 if(moduleName==='reminders')return {'MÃ NHẮC VIỆC':text(body.reminderId??body.id??data['MÃ NHẮC VIỆC']??'')||`NV${Date.now()}`,'NGÀY NHẮC':body.date??body.reminderDate??data['NGÀY NHẮC']??'','TIÊU ĐỀ NHẮC VIỆC':body.title??data['TIÊU ĐỀ NHẮC VIỆC']??'','NỘI DUNG / GHI CHÚ':body.note??data['NỘI DUNG / GHI CHÚ']??'','NGƯỜI LIÊN QUAN':body.person??data['NGƯỜI LIÊN QUAN']??'','TRẠNG THÁI':body.status??data['TRẠNG THÁI']??'CHƯA THỰC HIỆN'};
 if(moduleName==='violations')return {'Mã VP':text(body.id??data['Mã VP']??'')||`VP${Date.now()}`,'Ngày vi phạm':body.date??data['Ngày vi phạm']??'','Mã NV':body.staffId??data['Mã NV']??'','Họ tên':body.person??data['Họ tên']??'','Bộ phận':body.department??data['Bộ phận']??'','Mã lỗi':body.errorId??data['Mã lỗi']??'','Tên lỗi':body.errorName??data['Tên lỗi']??'','Mức độ':body.level??data['Mức độ']??'','Điểm trừ':body.score??data['Điểm trừ']??0,'Người ghi nhận':body.recorder??data['Người ghi nhận']??'','Ghi chú':body.note??data['Ghi chú']??'','Trạng thái':body.status??data['Trạng thái']??'Chưa xử lý','Hình ảnh':body.imageName??data['Hình ảnh']??data['Ảnh minh chứng']??''};
 if(moduleName==='violationError')return {'Mã lỗi':text(body.id??data['Mã lỗi']??'')||`L${Date.now()}`,'Tên lỗi':body.name??data['Tên lỗi']??'','Bộ phận':body.department??data['Bộ phận']??'','Mức độ':body.level??data['Mức độ']??'Nhắc nhở','Điểm trừ':body.score??data['Điểm trừ']??0,'Ghi chú':body.note??data['Ghi chú']??'','Trạng thái':body.status??data['Trạng thái']??'Hoạt động'};
 if(moduleName==='plans')return {'Mã KH':text(body.id??data['Mã KH']??'')||`KH${Date.now()}`,'Từ ngày':body.fromDate??data['Từ ngày']??'','Đến ngày':body.toDate??data['Đến ngày']??'','Bộ phận':body.department??data['Bộ phận']??'','Nội dung':body.content??data['Nội dung']??'','Người phụ trách':body.owner??data['Người phụ trách']??'','Trạng thái':body.status??data['Trạng thái']??'CHƯA BẮT ĐẦU','Kết quả':body.result??data['Kết quả']??'','Ghi chú':body.note??data['Ghi chú']??'','Ngày hoàn thành':body.completedAt??data['Ngày hoàn thành']??'','Nội dung / Mô tả':body.description??data['Nội dung / Mô tả']??data['Mô tả']??''};
 if(moduleName==='issues')return {'Mã TT':text(body.id??data['Mã TT']??'')||`TT${Date.now()}`,'Ngày ghi nhận':body.date??data['Ngày ghi nhận']??'','Bộ phận':body.department??data['Bộ phận']??'','Tồn tại / Sự cố / Kiến nghị':body.issue??data['Tồn tại / Sự cố / Kiến nghị']??'','Nguyên nhân':body.cause??data['Nguyên nhân']??'','Phương án khắc phục':body.action??data['Phương án khắc phục']??'','Người phụ trách':body.owner??data['Người phụ trách']??'','Hạn xử lý':body.deadline??data['Hạn xử lý']??'','Trạng thái':body.status??data['Trạng thái']??'CHƯA KHẮC PHỤC','Kiến nghị':body.recommendation??data['Kiến nghị']??'','Ghi chú':body.note??data['Ghi chú']??'','Loại nội dung':body.kind??data['Loại nội dung']??''};
 if(moduleName==='reports')return {'Mã ý kiến':text(body.opinionId??data['Mã ý kiến']??'')||`YK${Date.now()}`,'Từ ngày':body.fromDate??body.from??data['Từ ngày']??'','Đến ngày':body.toDate??body.to??data['Đến ngày']??'','Bộ phận':body.department??data['Bộ phận']??'','Nhân viên':body.person??data['Nhân viên']??'','Mã phiếu':body.formCode??body.reportId??data['Mã phiếu']??'','Tên phiếu':body.formName??data['Tên phiếu']??'','Ý kiến khắc phục của tổ trưởng':body.opinion??data['Ý kiến khắc phục của tổ trưởng']??'','Người nhập':body.enteredBy??data['Người nhập']??'','Trạng thái':body.status??data['Trạng thái']??'Đã lưu'};
 if(moduleName==='feedback')return {'Mã ý kiến':text(body.id??data['Mã ý kiến']??'')||`YK-KPI-${Date.now()}`,'Từ ngày':body.from??data['Từ ngày']??'','Đến ngày':body.to??data['Đến ngày']??'','Bộ phận':body.department??data['Bộ phận']??'','Nhân viên':body.person??data['Nhân viên']??'','Nội dung góp ý':body.text??data['Nội dung góp ý']??'','Người nhập':body.author??data['Người nhập']??'','Cập nhật lúc':new Date().toISOString()};
 if(moduleName==='rule')return {'STT':body.order??data['STT']??1,'Xếp loại':body.ranking??data['Xếp loại']??'','Từ điểm':body.min??data['Từ điểm']??0,'Đến điểm':body.max??data['Đến điểm']??0,'Màu':body.color??data['Màu']??'#6C757D','Trạng thái':body.status??data['Trạng thái']??'Hoạt động','Cập nhật lúc':new Date().toISOString()};
 if(moduleName==='checklistForm')return {'Mã phiếu':body.code??data['Mã phiếu']??'','Tên phiếu':body.name??data['Tên phiếu']??'','Bộ phận':body.department??data['Bộ phận']??'','Mô tả':body.description??data['Mô tả']??'','Trạng thái':body.status??data['Trạng thái']??'Hoạt động'};
 if(moduleName==='checklistCriterion')return {'Mã tiêu chí':text(body.id??data['Mã tiêu chí']??'')||`BK${Date.now()}`,'Mã phiếu':body.formCode??data['Mã phiếu']??'','Bộ phận':body.department??data['Bộ phận']??'','Nhóm tiêu chí':body.group??data['Nhóm tiêu chí']??'Chung','Nội dung tiêu chí':body.content??data['Nội dung tiêu chí']??'','Nội dung chi tiết':body.detail??data['Nội dung chi tiết']??body.content??'','STT':body.order??data.STT??'','Cho phép hình ảnh':body.allowImage??data['Cho phép hình ảnh']??'Có','Trạng thái':body.status??data['Trạng thái']??'Hoạt động'};
 if(moduleName==='kpi')return {'Thời gian lưu':body.date??new Date().toISOString(),'Từ ngày':body.fromDate??'','Đến ngày':body.toDate??'','Mã NV':body.staffId??'','Họ tên':body.person??body.name??'','Bộ phận':body.department??'','Chức vụ':body.position??'','Điểm gốc':body.base??100,'Điểm giao việc':body.taskScore??0,'Điểm bảng kiểm':body.checklistScore??0,'Điểm vi phạm':body.violationScore??0,'Tổng điểm':body.total??0,'Xếp loại':body.ranking??body.rank??'','Chi tiết':Array.isArray(body.details)?body.details.join(' | '):body.detail??''};
 return data;}
function sheetFor(moduleName:string,body:AnyRecord){return ({staff:S.staff,tasks:S.tasks,reminders:S.reminders,violations:S.violations,violationError:S.errors,issues:S.issues,reports:S.opinions,kpi:S.kpi,feedback:S.kpiFeedback,rule:S.kpiRules,checklistForm:S.checklistForms,checklistCriterion:S.checklistCriteria}[moduleName]||(moduleName==='plans'?(text(body.type).toUpperCase()==='THÁNG'?S.monthly:S.weekly):''));}
function findById(rows:LegacyRow[],id:string){return rows.find(r=>same(r.legacy_id,id)||same(pick(r.data,['ID','Mã công việc','Mã VP','Mã phiếu','Mã KH','Mã TT','MÃ NHẮC VIỆC','Mã NV']),id));}
function nextDate(value:string,days:number){const d=new Date(`${value}T00:00:00`);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10);}
function carryDates(from:string,to:string,type:string){if(type==='THÁNG'){const d=new Date(`${from||to}T00:00:00`);const first=new Date(d.getFullYear(),d.getMonth()+1,1);const last=new Date(d.getFullYear(),d.getMonth()+2,0);return {from:first.toISOString().slice(0,10),to:last.toISOString().slice(0,10)};}return {from:nextDate(from||to,7),to:nextDate(to||from,7)};}
function resolveTaskStaffName(staff:AnyRecord[],value:unknown,label:string,existing?:unknown){const input=text(value);if(!input&&label==='Người giao việc')return '';if(!input)throw new Error(`${label} không được để trống.`);const matched=staff.find(x=>same(x.name,input));if(matched)return text(matched.name);if(existing&&same(existing,input))return text(existing);throw new Error(`${label} phải được chọn từ danh sách nhân sự.`);}

async function saveChecklist(raw:AnyRecord){
 const details=Array.isArray(raw.details)?raw.details as AnyRecord[]:[];if(!details.length)throw new Error('Chưa có tiêu chí bảng kiểm.');const formCode=text(raw.formCode);const formName=text(raw.formName);if(!formCode||!formName)throw new Error('Phải chọn phiếu giám sát.');let applied=0,pass=0,fail=0,na=0;
 for(const [index,x] of details.entries()){const result=norm(x.result);if(!result)throw new Error(`Chưa chọn kết quả tại tiêu chí số ${index+1}.`);if(result==='n/a'||result==='khong ap dung'){na++;continue;}if(result!=='dat'&&result!=='khong dat'&&result!=='kem')throw new Error(`Kết quả không hợp lệ tại tiêu chí số ${index+1}.`);applied++;if(result==='dat')pass++;else{fail++;if(!text(x.note))throw new Error(`Tiêu chí không đạt số ${index+1} cần nhập ghi chú lỗi.`);}}
 const rate=applied?Math.round(pass*10000/applied)/100:0;const kpi=rate>=95?5:rate>=90?3:rate>=80?0:rate>=70?-3:-5;const id=`PGS${Date.now()}${Math.floor(Math.random()*1000)}`;const rowNo=await saveRow(S.checklists,undefined,{'Mã phiếu':id,'Ngày giám sát':raw.date||today(),'Mã NV':raw.staffId||'','Họ tên':raw.staffName||'','Bộ phận':raw.department||'','Người giám sát':raw.supervisor||'','Khu vực':raw.area||'','Ca':raw.shift||'','Tổng áp dụng':applied,'Đạt':pass,'Không đạt':fail,'Tỷ lệ %':rate,'Điểm KPI':kpi,'Ghi chú':raw.note||'','Ảnh minh chứng':'','Thời gian lưu':new Date().toISOString(),'Mã mẫu phiếu':formCode,'Tên phiếu':formName,'Không áp dụng':na,'Tỷ lệ % chấm':rate,'Xếp loại theo phiếu':rate>=95?'A':rate>=90?'B':rate>=80?'C':'CHƯA ĐẠT','KPI bảng kiểm áp dụng':kpi});let detailNo=await nextRowNo(S.checklistDetails);for(const x of details){await saveRow(S.checklistDetails,detailNo++,{'Mã phiếu':id,'Mã tiêu chí':x.criterionCode||x.id||'','Nhóm tiêu chí':x.group||'','Nội dung tiêu chí':x.content||'','Kết quả':x.result||'','Ghi chú':x.note||'','STT':x.order||'','Nội dung chi tiết':x.detail||'','Hình ảnh lỗi':x.errorImage||'','Hình ảnh khắc phục':x.fixImage||''});}return {id,row_no:rowNo,rate,kpi,pass,fail,na};
}
async function inlineUpdate(body:AnyRecord){const kind=text(body.kind).toUpperCase();const sheet=kind==='TASK'?S.tasks:kind==='PLAN'?(text(body.planType).toUpperCase()==='THÁNG'?S.monthly:S.weekly):kind==='VIOLATION'?S.violations:kind==='ISSUE'?S.issues:'';if(!sheet)throw new Error('Loại dữ liệu cập nhật không hỗ trợ.');const rows=await readSheet(sheet);const found=Number(body.row_no)?rows.find(x=>x.row_no===Number(body.row_no)):findById(rows,text(body.id));if(!found)throw new Error('Không tìm thấy bản ghi cần cập nhật.');const data={...found.data};if(kind==='TASK'){if(body.status!==undefined)data['Trạng thái NV']=body.status;if(body.evalStatus!==undefined)data['Đánh giá quản lý']=body.evalStatus;if(body.note!==undefined)data['Ghi chú quản lý']=body.note;}else if(kind==='PLAN'){if(body.status!==undefined)data['Trạng thái']=body.status;if(body.note!==undefined)data['Ghi chú']=body.note;if(body.description!==undefined)data['Nội dung / Mô tả']=body.description;}else{if(body.status!==undefined)data['Trạng thái']=body.status;if(body.note!==undefined)data['Ghi chú']=body.note;}await saveRow(sheet,found.row_no,data);return {row_no:found.row_no};}

export async function GET(req:Request){if(!await hasSession())return NextResponse.json({ok:false,error:'Chưa đăng nhập'},{status:401});try{const url=new URL(req.url);const moduleName=text(url.searchParams.get('module'))||'tasks';const result=await buildModule(moduleName,parseFilters(url));return NextResponse.json({ok:true,module:moduleName,...result},{headers:{'Cache-Control':'private, no-store'}});}catch(error){console.error('[modules:get]',error);return NextResponse.json({ok:false,error:'Không tải được dữ liệu phân hệ',detail:error instanceof Error?error.message:'Lỗi Supabase'},{status:503});}}
export async function POST(req:Request){if(!await hasSession())return NextResponse.json({ok:false,error:'Chưa đăng nhập'},{status:401});try{const body=(await req.json()) as AnyRecord;const moduleName=text(body.module);const op=text(body.op)||'save';
 if(op==='delete'){await deleteRow(text(body.sheet)||sheetFor(moduleName,body),Number(body.row_no));return NextResponse.json({ok:true});}
 if(op==='inline')return NextResponse.json({ok:true,...await inlineUpdate(body)});
 if(moduleName==='checklists'&&(op==='save'||!op))return NextResponse.json({ok:true,...await saveChecklist(body.data||body)});
 if(moduleName==='plans'&&['complete','reset','plan_status'].includes(op)){const sheet=sheetFor('plans',body);const row=await readRow(sheet,Number(body.row_no));if(!row)throw new Error('Không tìm thấy kế hoạch.');const data={...row.data};const status=op==='complete'?'HOÀN THÀNH':op==='reset'?'CHƯA BẮT ĐẦU':body.status||'CHƯA BẮT ĐẦU';data['Trạng thái']=status;data['Kết quả']=body.result??data['Kết quả']??'';data['Ngày hoàn thành']=status==='HOÀN THÀNH'?today():'';await saveRow(sheet,row.row_no,data);return NextResponse.json({ok:true,row_no:row.row_no});}
 if(moduleName==='plans'&&op==='carry'){const sheet=sheetFor('plans',body);const row=await readRow(sheet,Number(body.row_no));if(!row)throw new Error('Không tìm thấy kế hoạch cần chuyển tiếp.');const old=plan(row,text(body.type).toUpperCase()||'TUẦN');const next=carryDates(old.fromDate,old.toDate,old.type);await saveRow(sheet,row.row_no,{...row.data,'Trạng thái':'CHUYỂN TIẾP','Kỳ chuyển tiếp':old.type==='THÁNG'?'THÁNG SAU':'TUẦN SAU'});const newId=old.type==='THÁNG'?`KHM${Date.now()}`:`KHT${Date.now()}`;const newRow=await saveRow(sheet,undefined,{...row.data,'Mã KH':newId,'Từ ngày':next.from,'Đến ngày':next.to,'Trạng thái':'CHƯA BẮT ĐẦU','Kết quả':'','Ngày hoàn thành':'','Mã kế hoạch gốc':old.rootId||old.id,'Kỳ chuyển tiếp':old.type==='THÁNG'?'THÁNG SAU':'TUẦN SAU'});return NextResponse.json({ok:true,row_no:newRow,id:newId});}
 if(moduleName==='kpi'&&op==='save_report'){const allStaff=getStaff(await readSheet(S.staff));const result=await buildKpi({from:text(body.fromDate),to:text(body.toDate),department:text(body.department),person:text(body.person)},allStaff,[],staffMap(allStaff));const rows=result.rows as AnyRecord[];for(const x of rows)await saveRow(S.kpi,undefined,canonical('kpi',{...x,fromDate:body.fromDate,toDate:body.toDate}));return NextResponse.json({ok:true,savedCount:rows.length});}
 if(moduleName==='feedback'&&(op==='save_feedback'||op==='save')){const rows=await readSheet(S.kpiFeedback);const found=rows.find(r=>same(pick(r.data,['Từ ngày']),body.from)&&same(pick(r.data,['Đến ngày']),body.to)&&same(pick(r.data,['Bộ phận']),body.department)&&same(pick(r.data,['Nhân viên']),body.person));const rowNo=await saveRow(S.kpiFeedback,found?.row_no,canonical('feedback',body));return NextResponse.json({ok:true,row_no:rowNo});}
 if(moduleName==='rule'&&op==='save_rules'){const rows=Array.isArray(body.rows)?body.rows as AnyRecord[]:[];for(const x of rows)await saveRow(S.kpiRules,Number(x.row_no)||undefined,canonical('rule',x));return NextResponse.json({ok:true,savedCount:rows.length});}
 const sheet=sheetFor(moduleName,body);if(!sheet)throw new Error('Thiếu sheet phân hệ.');const data=canonical(moduleName,body);if(moduleName==='tasks'){if(!text(data['Tiêu đề công việc']))throw new Error('Tiêu đề công việc không được để trống.');const staffList=getStaff(await readSheet(S.staff));const oldData=body.data&&typeof body.data==='object'?body.data as AnyRecord:{};data['Người thực hiện']=resolveTaskStaffName(staffList,data['Người thực hiện'],'Người thực hiện',oldData['Người thực hiện']);data['Người giao việc']=resolveTaskStaffName(staffList,data['Người giao việc'],'Người giao việc',oldData['Người giao việc']);data['Bộ phận']=text(data['Bộ phận'])||staffList.find(x=>same(x.name,data['Người thực hiện']))?.department||'';data['Thuộc bộ phận']=data['Bộ phận'];}if(moduleName==='issues'&&!text(data['Tồn tại / Sự cố / Kiến nghị']))throw new Error('Nội dung tồn tại/kiến nghị không được để trống.');const rowNo=await saveRow(sheet,Number(body.row_no)||undefined,data);return NextResponse.json({ok:true,row_no:rowNo,id:text(data['Mã phiếu']||data['Mã KH']||data['Mã VP']||data['Mã TT']||data['MÃ NHẮC VIỆC']||data.ID||'')});
 }catch(error){console.error('[modules:post]',error);return NextResponse.json({ok:false,error:error instanceof Error?error.message:'Không lưu được dữ liệu'},{status:503});}}
